<style type="text/css">
    .header_top                                        {width:100%; height:80px; background:url(<?php echo $this->baseUrl('/img/user_top_bg.gif')?>); clear:both;}
    .header_top .logo                                  {width:880px; clear:both;}
    .header_top .logo .left                            {width:300px; height:80px; background-color:#FFFFFF; float:left;}
    .header_top .logo .right                           {width:550px; height:80px; float:right;}

    
    
</style>

<div class="cell_h"></div>
<div class="header_top">
    <div class="logo">
        <div class="left">
            <a href="<?php echo $this->baseUrl('/')?>"><img src="<?php echo $this->baseUrl('/img/logo.jpg')?>" style="margin-top:13px; border:0px;"/></a>
        </div>
        <div class="right">
    
        </div>
    </div>
</div>
<div class="cell_h"></div>

