<style type="text/css">
    .index_frame1                                         {width:960px; clear:both;}
    .index_frame1 .left                                   {width:308px; height:348px; float:left; background-color:#E7F6FB; border:2px solid #DDDDDD;}  
    .index_frame1 .center                                 {width:336px; height:350px; margin-left:10px; float:left; background:url(<?php echo $this->baseUrl('/img/news_bg.jpg')?>); border:1px solid #92C7ED;}                        
    .index_frame1 .center .li1                            {width:95%; height:26px; line-height:26px; text-align:left; color:#FF0000; overflow:hidden; clear:both;}
    .index_frame1 .center .li2                            {width:95%; height:56px; line-height:23px; font-size:12px; color:#666666; border-bottom:1px dashed #C2C2C2; overflow:hidden; clear:both;}
    .index_frame1 .center .li3                            {width:95%; height:26px; line-height:26px; text-align:left; overflow:hidden; clear:both;}
    .index_frame1 .right                                  {width:290px; height:350px; float:right;}                        
    .index_frame1 .right .p1                              {margin-left:0px; margin-right:0px; height:138px; border:1px solid #92C7ED; clear:both;} 
    .index_frame1 .right .p1 .title                       {margin-left:0px; margin-right:0px; position:relative; height:28px; line-height:28px; color:#0257AE; text-align:left; background:url(<?php echo $this->baseUrl('/img/title_bg1.gif')?>); border:1px solid #FFFFFF; clear:both;}
    .index_frame1 .right .p1 .content                     {margin-left:0px; margin-right:0px; clear:both;}
    .index_frame1 .right .p1 .content li                  {width:95%; height:26px; line-height:26px; text-align:left; overflow:hidden; clear:both;} 
    .index_frame1 .right .p2                              {margin-left:0px; margin-right:0px; height:200px; border:1px solid #92C7ED; clear:both;} 
    .index_frame1 .right .p2 .title                       {margin-left:0px; margin-right:0px; position:relative; height:28px; line-height:28px; color:#0257AE; text-align:left; background:url(<?php echo $this->baseUrl('/img/title_bg1.gif')?>); border:1px solid #FFFFFF; clear:both;}
    .index_frame1 .right .p2 .content                     {margin-left:0px; margin-right:0px; clear:both;}
    .index_frame1 .right .p2 .content .np1                {width:49%; height:105px; line-height:22px; float:left;}
    .index_frame1 .right .p2 .content .np2                {width:95%; height:26px; line-height:26px; text-align:left; overflow:hidden;}
    .index_frame2                                         {width:960px; clear:both;}
    .index_frame2 .left                                   {width:660px; float:left;}
    .index_frame2 .left .p1                               {margin-left:0px; margin-right:0px; clear:both;}             
    .index_frame2 .left .p1 .l                            {width:323px; height:240px; border:1px solid #92C7ED; float:left;}
    .index_frame2 .left .p1 .r                            {width:323px; height:240px; border:1px solid #92C7ED; float:right;}
    .index_frame2 .left .p1 .title                        {margin-left:0px; margin-right:0px; position:relative; height:28px; line-height:28px; color:#0257AE; text-align:left; background:url(<?php echo $this->baseUrl('/img/title_bg1.gif')?>); border:1px solid #FFFFFF; clear:both;}
    .index_frame2 .left .p1 .l .content1                  {width:95%; clear:both;}
    .index_frame2 .left .p1 .l .content2                  {width:95%; height:26px; line-height:26px; text-align:left; overflow:hidden; clear:both;}
    .index_frame2 .left .p1 .l .content1 .cl              {width:40%; height:100px; float:left;}
    .index_frame2 .left .p1 .l .content1 .cr              {width:58%; height:100px; float:right;}
    .index_frame2 .left .p1 .l .content1 .cr .li1         {margin-left:0px; margin-right:0px; height:30px; line-height:30px; clear:both;}
    .index_frame2 .left .p1 .l .content1 .cr .li2         {margin-left:0px; margin-right:0px; height:60px; line-height:20px; text-align:left; color:#888888; clear:both;}
    .index_frame2 .left .p1 .r .content1                  {width:95%; clear:both;}
    .index_frame2 .left .p1 .r .content2                  {width:95%; height:26px; line-height:26px; text-align:left; overflow:hidden; clear:both;}
    .index_frame2 .left .p1 .r .content1 .cl              {width:40%; height:100px; float:left;}
    .index_frame2 .left .p1 .r .content1 .cr              {width:58%; height:100px; float:right;}
    .index_frame2 .left .p1 .r .content1 .cr .li1         {margin-left:0px; margin-right:0px; height:30px; line-height:30px; clear:both;}
    .index_frame2 .left .p1 .r .content1 .cr .li2         {margin-left:0px; margin-right:0px; height:60px; line-height:20px; text-align:left; color:#888888; clear:both;}
    .index_frame2 .left .p2                               {margin-left:0px; margin-right:0px; clear:both;}             
    .index_frame2 .left .p2 .l                            {width:323px; height:240px; border:1px solid #92C7ED; float:left;}
    .index_frame2 .left .p2 .r                            {width:323px; height:240px; border:1px solid #92C7ED; float:right;}
    .index_frame2 .left .p2 .title                        {margin-left:0px; margin-right:0px; position:relative; height:28px; line-height:28px; text-align:left; color:#0257AE; background:url(<?php echo $this->baseUrl('/img/title_bg1.gif')?>); border:1px solid #FFFFFF; clear:both;}
    .index_frame2 .left .p2 .l .content1                  {width:95%; clear:both;}
    .index_frame2 .left .p2 .l .content2                  {width:95%; height:26px; line-height:26px; text-align:left; overflow:hidden; clear:both;}
    .index_frame2 .left .p2 .l .content1 .cl              {width:40%; height:100px; float:left;}
    .index_frame2 .left .p2 .l .content1 .cr              {width:58%; height:100px; float:right;}
    .index_frame2 .left .p2 .l .content1 .cr .li1         {margin-left:0px; margin-right:0px; height:30px; line-height:30px; clear:both;}
    .index_frame2 .left .p2 .l .content1 .cr .li2         {margin-left:0px; margin-right:0px; height:60px; line-height:20px; text-align:left; color:#888888; clear:both;}
    .index_frame2 .left .p2 .r .content1                  {width:95%; clear:both;}
    .index_frame2 .left .p2 .r .content2                  {width:95%; height:26px; line-height:26px; text-align:left; overflow:hidden; clear:both;}
    .index_frame2 .left .p2 .r .content1 .cl              {width:40%; height:100px; float:left;}
    .index_frame2 .left .p2 .r .content1 .cr              {width:58%; height:100px; float:right;}
    .index_frame2 .left .p2 .r .content1 .cr .li1         {margin-left:0px; margin-right:0px; height:30px; line-height:30px; clear:both;}
    .index_frame2 .left .p2 .r .content1 .cr .li2         {margin-left:0px; margin-right:0px; height:60px; line-height:20px; text-align:left; color:#888888; clear:both;}
    .index_frame2 .left .p3                               {margin-left:0px; margin-right:0px; clear:both;}             
    .index_frame2 .left .p3 .l                            {width:323px; height:240px; border:1px solid #92C7ED; float:left;}
    .index_frame2 .left .p3 .r                            {width:323px; height:240px; border:1px solid #92C7ED; float:right;}
    .index_frame2 .left .p3 .title                        {margin-left:0px; margin-right:0px; position:relative; height:28px; line-height:28px; color:#0257AE; text-align:left; background:url(<?php echo $this->baseUrl('/img/title_bg1.gif')?>); border:1px solid #FFFFFF; clear:both;}
    .index_frame2 .left .p3 .l .content1                  {width:95%; clear:both;}
    .index_frame2 .left .p3 .l .content2                  {width:95%; height:26px; line-height:26px; text-align:left; overflow:hidden; clear:both;}
    .index_frame2 .left .p3 .l .content1 .cl              {width:40%; height:100px; float:left;}
    .index_frame2 .left .p3 .l .content1 .cr              {width:58%; height:100px; float:right;}
    .index_frame2 .left .p3 .l .content1 .cr .li1         {margin-left:0px; margin-right:0px; height:30px; line-height:30px; clear:both;}
    .index_frame2 .left .p3 .l .content1 .cr .li2         {margin-left:0px; margin-right:0px; height:60px; line-height:20px; text-align:left; color:#888888; clear:both;}
    .index_frame2 .left .p3 .r .content1                  {width:95%; clear:both;}
    .index_frame2 .left .p3 .r .content2                  {width:95%; height:26px; line-height:26px; text-align:left; overflow:hidden; clear:both;}
    .index_frame2 .left .p3 .r .content1 .cl              {width:40%; height:100px; float:left;}
    .index_frame2 .left .p3 .r .content1 .cr              {width:58%; height:100px; float:right;}
    .index_frame2 .left .p3 .r .content1 .cr .li1         {margin-left:0px; margin-right:0px; height:30px; line-height:30px; clear:both;}
    .index_frame2 .left .p3 .r .content1 .cr .li2         {margin-left:0px; margin-right:0px; height:60px; line-height:20px; text-align:left; color:#888888; clear:both;}
    .index_frame2 .left .p4                               {margin-left:0px; margin-right:0px; height:160px; border:1px solid #92C7ED; clear:both;} 
    .index_frame2 .left .p4 .content                      {margin-left:0px; margin-right:0px; height:119px; clear:both;}
    .index_frame2 .left .p4 .content li                   {width:164px; height:130px; line-height:30px; overflow:hidden; float:left;}
    .index_frame2 .left .p4 .title                        {margin-left:0px; margin-right:0px; position:relative; height:28px; line-height:28px; text-align:left; color:#0257AE; background:url(<?php echo $this->baseUrl('/img/title_bg1.gif')?>); border:1px solid #FFFFFF; clear:both;}
    .index_frame2 .right                                  {width:290px; float:right;}
    .index_frame2 .right .p1                              {margin-left:0px; margin-right:0px; height:330px; border:1px solid #92C7ED; clear:both;}    
    .index_frame2 .right .p1 .title                       {margin-left:0px; margin-right:0px; position:relative; height:28px; line-height:28px; text-align:left; color:#0257AE; background:url(<?php echo $this->baseUrl('/img/title_bg1.gif')?>); border:1px solid #FFFFFF; clear:both;}
    .index_frame2 .right .p1 .content                     {margin-left:0px; margin-right:0px; clear:both;}
    .index_frame2 .right .p1 .content li                  {width:95%; height:26px; line-height:26px; text-align:left; overflow:hidden; clear:both;} 
    .index_frame2 .right .p2                              {margin-left:0px; margin-right:0px; height:326px; border:1px solid #92C7ED; clear:both;}    
    .index_frame2 .right .p2 .title                       {margin-left:0px; margin-right:0px; position:relative; height:28px; line-height:28px; color:#0257AE; text-align:left; background:url(<?php echo $this->baseUrl('/img/title_bg1.gif')?>); border:1px solid #FFFFFF; clear:both;}
    .index_frame2 .right .p2 .content1                    {width:95%; clear:both;}
    .index_frame2 .right .p2 .content2                    {width:95%; height:26px; line-height:26px; text-align:left; overflow:hidden; clear:both;}
    .index_frame2 .right .p2 .content1 .cl                {width:40%; height:100px; float:left;}
    .index_frame2 .right .p2 .content1 .cr                {width:58%; height:100px; float:right;}
    .index_frame2 .right .p2 .content1 .cr .li1           {margin-left:0px; margin-right:0px; height:30px; line-height:30px; clear:both;}
    .index_frame2 .right .p2 .content1 .cr .li2           {margin-left:0px; margin-right:0px; height:60px; line-height:20px; text-align:left; color:#888888; clear:both;}
    .index_frame2 .right .p3                              {margin-left:0px; margin-right:0px; height:326px; border:1px solid #92C7ED; clear:both;}    
    .index_frame2 .right .p3 .title                       {margin-left:0px; margin-right:0px; position:relative; height:28px; line-height:28px; color:#0257AE; text-align:left; background:url(<?php echo $this->baseUrl('/img/title_bg1.gif')?>); border:1px solid #FFFFFF; clear:both;}
    .index_frame2 .right .p3 .content                     {margin-left:0px; margin-right:0px; clear:both;}
    .index_frame2 .right .p3 .content li                  {width:95%; height:26px; line-height:26px; text-align:left; overflow:hidden; clear:both;}
    
</style>

<div class="index_frame1">
    <div class="left">
        <script language="javascript">        
        //广告宽度
        var w = "308";
        
        //广告高度
        var h = "348";
        
        //小广告高度
        var h1 = "60";
        
        //图片地址
        var imgSrc = new Array;
        imgSrc[0] = '<?php echo $this->baseUrl('/upfile/ad/news_1.jpg')?>';
        imgSrc[1] = '<?php echo $this->baseUrl('/upfile/ad/news_2.jpg')?>';
        imgSrc[2] = '<?php echo $this->baseUrl('/upfile/ad/news_3.jpg')?>';
        imgSrc[3] = '<?php echo $this->baseUrl('/upfile/ad/news_4.jpg')?>';
        
        //图片链接地址
        var imgLink = new Array;
        imgLink[0] = 'http://www.mrbooks.cn';
        imgLink[1] = 'http://www.mrbccd.com';
        imgLink[2] = 'http://www.mrbooks.cn/listsepbook-sepprice.html';
        imgLink[3] = 'booksjs.php?stypeid=12';
        
        //图片链接提示文字
        var imgLinkTitle = new Array;
        imgLinkTitle[0] = '吉林省明日科技有限公司将推出编程词典<br /><font style="color:#FFB900; font-size:12px; font-weight:normal">预计将于2008年8月20日震撼推出</font>';
        imgLinkTitle[1] = '明日网络学院<br /><font style="color:#FFB900; font-size:12px; font-weight:normal">最专业、最前面的IT技术视频网站</font>';
        imgLinkTitle[2] = '明日网上书店<br /><font style="color:#FFB900; font-size:12px; font-weight:normal">预计将于2008年8月20日开业</font>';
        imgLinkTitle[3] = '编程词典服务社区<br /><font style="color:#FFB900; font-size:12px; font-weight:normal">国内最具势力的IT技术服务专区</font>';
        </script>
        <script src="<?php echo $this->baseUrl('/js/lzhScrollImg.js')?>"></script>
    </div>
    <div class="center">
        <ul>
            <li class="li1">
                [今日推荐]
            </li>
        <?php foreach ($this->todayCommendNewses as $key => $todayCommendNews):?>
            <?php if($key < 2):?>
            <li class="li2"><a href="<?php echo $this->baseUrl('/news/info-'.$todayCommendNews['id'].'-1.html')?>" title="<?php echo $this->escape($todayCommendNews['title'])?>" class="<?php if($key == 0):?>a5<?php else:?>a6<?php endif;?>"><?php echo $this->substr($this->escape($todayCommendNews['title']), 50)?></a><br/>[<?php echo $this->substr($todayCommendNews['uncontent'], 60)?>]</li>
            <?php else:?>
            <li class="li3">·<a href="<?php echo $this->baseUrl('/news/info-'.$todayCommendNews['id'].'-1.html')?>" title="<?php echo $this->escape($todayCommendNews['title'])?>"><?php echo $this->substr($this->escape($todayCommendNews['title']), 60)?></a></li>
            <?php endif;?>
        <?php endforeach;?>
        </ul>
    </div>
    <div class="right">
        <div class="p1">
            <div class="title">
                <img src="<?php echo $this->baseUrl('/img/title_mark1.gif')?>" style="position:absolute; left:8px; top:9px;" alt="热门新闻" />　　热门新闻　　　　　　　　　　　　　<a href="<?php echo $this->baseUrl('/news/list-all-2-1.html')?>" class="a7">[更多]</a>
            </div>
            <div class="content">
                <ul>
                    <?php foreach ($this->hotNewses as $hotNews):?>
                    <li>·<a href="<?php echo $this->baseUrl('/news/info-'.$hotNews['id'].'-1.html')?>" title="<?php echo $this->escape($hotNews['title'])?>"><?php echo $this->substr($this->escape($hotNews['title']), 40)?></a>&nbsp;<font style="font-size:11px; color:#666666; font-family:Arial;">/<?php echo $hotNews['browse']?>/</font></li>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
        <div class="cell_h"></div>
        <div class="p2">
            <div class="title">
                <img src="<?php echo $this->baseUrl('/img/title_mark1.gif')?>" style="position:absolute; left:8px; top:9px;" alt="IT人物"/>　　IT人物　　　　　　　　　　　　　<a href="<?php echo $this->baseUrl('/news/list-1-0-1.html')?>" class="a7">[更多]</a>
            </div>
            <div class="content">
                <?php foreach ($this->personNewses as $key => $personNews):?>
                    <?php if($key < 2):?>
                <div class="np1">
                    <a href="<?php echo $this->baseUrl('/news/info-'.$personNews['id'].'-1.html')?>"><img src="<?php echo $this->baseUrl('/upfile/file/'.$personNews['imagename'])?>" style="width:110px; height:73px; margin-top:8px; border:1px solid #40D70B" onmouseover="this.style.borderColor='#CCCCCC'" onmouseout="this.style.borderColor='#40D70B'" alt="<?php echo $this->escape($personNews['title'])?>"/></a> 
                    <br/><a href="<?php echo $this->baseUrl('/news/info-'.$personNews['id'].'-1.html')?>" title="<?php echo $this->escape($personNews['title'])?>" class="a24"><?php echo $this->substr($this->escape($personNews['title']), 20)?></a>
                </div>
                    <?php endif;?>
                    <?php if($key == 2):?>
                <div class="clear"></div>
                    <?php endif;?>   
                    <?php if($key > 1):?>  
                <div class="np2">
                    ·<a href="<?php echo $this->baseUrl('/news/info-'.$personNews['id'].'-1.html')?>" title="<?php echo $this->escape($personNews['title'])?>"><?php echo $this->substr($this->escape($personNews['title']), 48)?></a>
                </div>  
                    <?php endif;?>   
                <?php endforeach;?>
            </div>
        </div>
    </div>
    <div class="clear"></div>      
</div>
<div class="cell_h"></div>
<div class="index_frame2">
    <div class="left">
        <div style="margin-left:0px; margin-right:0px; height:80px; background-color:#CCCCCC;">
        
        </div>
        <div class="cell_h"></div>
        <!-- p1  -->
        <div class="p1">
            <div class="l">
                <div class="title">
                    <img src="<?php echo $this->baseUrl('/img/title_mark1.gif')?>" style="position:absolute; left:8px; top:9px;" alt="产品快讯"/>　　产品快讯　　　　　　　　　　　　　　　<a href="<?php echo $this->baseUrl('/news/list-3-0-1.html')?>" class="a7">[更多]</a>
                </div>
                <?php foreach ($this->productNewses as $key => $productNews):?>
                    <?php if($key == 0):?>
                <div class="content1">
                    <div class="cl">
                        <a href="<?php echo $this->baseUrl('/news/info-'.$productNews['id'].'-1.html')?>"><img src="<?php echo $this->baseUrl('/upfile/file/'.$productNews['imagename'])?>" style="width:110px; height:73px; margin-top:8px; border:1px solid #40D70B" onmouseover="this.style.borderColor='#CCCCCC'" onmouseout="this.style.borderColor='#40D70B'" alt="<?php echo $this->escape($productNews['title'])?>"/></a> 
                    </div>
                    <div class="cr">
                        <ul>
                            <li class="li1"><a href="<?php echo $this->baseUrl('/news/info-'.$productNews['id'].'-1.html')?>" title="<?php echo $this->escape($productNews['title'])?>" class="a24"><?php echo $this->substr($this->escape($productNews['title']), 30)?></a></li>
                            <li class="li2">　　<?php echo trim($this->substr($this->escape($productNews['uncontent']), 85))?><a href="<?php echo $this->baseUrl('/news/info-'.$productNews['id'].'-1.html')?>" class="a3">&lt;详细&gt;</a></li>
                        </ul>
                    </div>
                    <div class="clear"></div>
                </div>
                    <?php else:?>
                <div class="content2">
                    ·<a href="<?php echo $this->baseUrl('/news/info-'.$productNews['id'].'-1.html')?>" title="<?php echo $this->escape($productNews['title'])?>"><?php echo $this->substr($this->escape($productNews['title']), 58)?></a> 
                </div>    
                    <?php endif;?>
                <?php endforeach;?>
            </div>
            <div class="r">
                <div class="title">
                    <img src="<?php echo $this->baseUrl('/img/title_mark1.gif')?>" style="position:absolute; left:8px; top:9px;" alt="企业动态"/>　　企业动态　　　　　　　　　　　　　　　<a href="<?php echo $this->baseUrl('/news/list-4-0-1.html')?>" class="a7">[更多]</a>
                </div>
                <?php foreach ($this->corporationNewses as $key => $corporationNews):?>
                    <?php if($key == 0):?>
                <div class="content1">
                    <div class="cl">
                        <a href="<?php echo $this->baseUrl('/news/info-'.$corporationNews['id'].'-1.html')?>"><img src="<?php echo $this->baseUrl('/upfile/file/'.$corporationNews['imagename'])?>" style="width:110px; height:73px; margin-top:8px; border:1px solid #40D70B" onmouseover="this.style.borderColor='#CCCCCC'" onmouseout="this.style.borderColor='#40D70B'" alt="<?php echo $this->escape($corporationNews['title'])?>"/></a> 
                    </div>
                    <div class="cr">
                        <ul>
                            <li class="li1"><a href="<?php echo $this->baseUrl('/news/info-'.$corporationNews['id'].'-1.html')?>" title="<?php echo $this->escape($corporationNews['title'])?>" class="a24"><?php echo $this->substr($this->escape($corporationNews['title']), 30)?></a></li>
                            <li class="li2">　　<?php echo trim($this->substr($this->escape($corporationNews['uncontent']), 85))?><a href="<?php echo $this->baseUrl('/news/info-'.$corporationNews['id'].'-1.html')?>" class="a3">&lt;详细&gt;</a></li>
                        </ul>
                    </div>
                    <div class="clear"></div>
                </div>
                    <?php else:?>
                <div class="content2">
                    ·<a href="<?php echo $this->baseUrl('/news/info-'.$corporationNews['id'].'-1.html')?>" title="<?php echo $this->escape($corporationNews['title'])?>"><?php echo $this->substr($this->escape($corporationNews['title']), 58)?></a> 
                </div>    
                    <?php endif;?>
                <?php endforeach;?>
            </div>
            <div class="clear"></div>
        </div>
        <div class="cell_h"></div>
        <!--  p2 -->
        <div class="p2">
            <div class="l">
                <div class="title">
                    <img src="<?php echo $this->baseUrl('/img/title_mark1.gif')?>" style="position:absolute; left:8px; top:9px;" alt="互联网"/>　　互联网　　　　　　　　　　　　　　　　<a href="<?php echo $this->baseUrl('/news/list-5-0-1.html')?>" class="a7">[更多]</a>
                </div>
                <?php foreach ($this->netNewses as $key => $netNews):?>
                    <?php if($key == 0):?>
                <div class="content1">
                    <div class="cl">
                        <a href="<?php echo $this->baseUrl('/news/info-'.$netNews['id'].'-1.html')?>"><img src="<?php echo $this->baseUrl('/upfile/file/'.$netNews['imagename'])?>" style="width:110px; height:73px; margin-top:8px; border:1px solid #40D70B" onmouseover="this.style.borderColor='#CCCCCC'" onmouseout="this.style.borderColor='#40D70B'" alt="<?php echo $this->escape($netNews['title'])?>"/></a> 
                    </div>
                    <div class="cr">
                        <ul>
                            <li class="li1"><a href="<?php echo $this->baseUrl('/news/info-'.$netNews['id'].'-1.html')?>" title="<?php echo $this->escape($netNews['title'])?>" class="a24"><?php echo $this->substr($this->escape($netNews['title']), 30)?></a></li>
                            <li class="li2">　　<?php echo trim($this->substr($this->escape($netNews['uncontent']), 85))?><a href="<?php echo $this->baseUrl('/news/info-'.$netNews['id'].'-1.html')?>" class="a3">&lt;详细&gt;</a></li>
                        </ul>
                    </div>
                    <div class="clear"></div>
                </div>
                    <?php else:?>
                <div class="content2">
                    ·<a href="<?php echo $this->baseUrl('/news/info-'.$netNews['id'].'-1.html')?>" title="<?php echo $this->escape($netNews['title'])?>"><?php echo $this->substr($this->escape($netNews['title']), 58)?></a> 
                </div>    
                    <?php endif;?>
                <?php endforeach;?>
            </div>
            <div class="r">
                <div class="title">
                    <img src="<?php echo $this->baseUrl('/img/title_mark1.gif')?>" style="position:absolute; left:8px; top:9px;" alt="游戏资讯"/>　　游戏资讯　　　　　　　　　　　　　　　<a href="<?php echo $this->baseUrl('/news/list-6-0-1.html')?>" class="a7">[更多]</a>
                </div>
                <?php foreach ($this->gameNewses as $key => $gameNews):?>
                    <?php if($key == 0):?>
                <div class="content1">
                    <div class="cl">
                        <a href="<?php echo $this->baseUrl('/news/info-'.$gameNews['id'].'-1.html')?>"><img src="<?php echo $this->baseUrl('/upfile/file/'.$gameNews['imagename'])?>" style="width:110px; height:73px; margin-top:8px; border:1px solid #40D70B" onmouseover="this.style.borderColor='#CCCCCC'" onmouseout="this.style.borderColor='#40D70B'" alt="<?php echo $this->escape($gameNews['title'])?>"/></a> 
                    </div>
                    <div class="cr">
                        <ul>
                            <li class="li1"><a href="<?php echo $this->baseUrl('/news/info-'.$gameNews['id'].'-1.html')?>" title="<?php echo $this->escape($gameNews['title'])?>" class="a24"><?php echo $this->substr($this->escape($gameNews['title']), 30)?></a></li>
                            <li class="li2">　　<?php echo trim($this->substr($this->escape($gameNews['uncontent']), 85))?><a href="<?php echo $this->baseUrl('/news/info-'.$gameNews['id'].'-1.html')?>" class="a3">&lt;详细&gt;</a></li>
                        </ul>
                    </div>
                    <div class="clear"></div>
                </div>
                    <?php else:?>
                <div class="content2">
                    ·<a href="<?php echo $this->baseUrl('/news/info-'.$gameNews['id'].'-1.html')?>" title="<?php echo $this->escape($gameNews['title'])?>"><?php echo $this->substr($this->escape($gameNews['title']), 58)?></a> 
                </div>    
                    <?php endif;?>
                <?php endforeach;?>
            </div>
            <div class="clear"></div>
        </div> 
        <!--  -->
        <div class="cell_h"></div>
        <div style="margin-left:0px; margin-right:0px; height:80px; background-color:#CCCCCC;">
        
        </div>
        <div class="cell_h"></div>
        <!--  p3 -->
        <div class="p3">
            <div class="l">
                <div class="title">
                    <img src="<?php echo $this->baseUrl('/img/title_mark1.gif')?>" style="position:absolute; left:8px; top:9px;" alt="广告传媒"/>　　广告传媒　　　　　　　　　　　　　　　<a href="<?php echo $this->baseUrl('/news/list-7-0-1.html')?>" class="a7">[更多]</a>
                </div>
                <?php foreach ($this->adNewses as $key => $adNews):?>
                    <?php if($key == 0):?>
                <div class="content1">
                    <div class="cl">
                        <a href="<?php echo $this->baseUrl('/news/info-'.$adNews['id'].'-1.html')?>"><img src="<?php echo $this->baseUrl('/upfile/file/'.$adNews['imagename'])?>" style="width:110px; height:73px; margin-top:8px; border:1px solid #40D70B" onmouseover="this.style.borderColor='#CCCCCC'" onmouseout="this.style.borderColor='#40D70B'" alt="<?php echo $this->escape($adNews['title'])?>"/></a> 
                    </div>
                    <div class="cr">
                        <ul>
                            <li class="li1"><a href="<?php echo $this->baseUrl('/news/info-'.$adNews['id'].'-1.html')?>" title="<?php echo $this->escape($adNews['title'])?>" class="a24"><?php echo $this->substr($this->escape($adNews['title']), 30)?></a></li>
                            <li class="li2">　　<?php echo trim($this->substr($this->escape($adNews['uncontent']), 85))?><a href="<?php echo $this->baseUrl('/news/info-'.$adNews['id'].'-1.html')?>" class="a3">&lt;详细&gt;</a></li>
                        </ul>
                    </div>
                    <div class="clear"></div>
                </div>
                    <?php else:?>
                <div class="content2">
                    ·<a href="<?php echo $this->baseUrl('/news/info-'.$adNews['id'].'-1.html')?>" title="<?php echo $this->escape($adNews['title'])?>"><?php echo $this->substr($this->escape($adNews['title']), 58)?></a> 
                </div>    
                    <?php endif;?>
                <?php endforeach;?>
            </div>
            <div class="r">
                <div class="title">
                    <img src="<?php echo $this->baseUrl('/img/title_mark1.gif')?>" style="position:absolute; left:8px; top:9px;" alt="财经报道"/>　　财经报道　　　　　　　　　　　　　　　<a href="<?php echo $this->baseUrl('/news/list-8-0-1.html')?>" class="a7">[更多]</a>
                </div>
                <?php foreach ($this->cjNewses as $key => $cjNews):?>
                    <?php if($key == 0):?>
                <div class="content1">
                    <div class="cl">
                        <a href="<?php echo $this->baseUrl('/news/info-'.$cjNews['id'].'-1.html')?>"><img src="<?php echo $this->baseUrl('/upfile/file/'.$cjNews['imagename'])?>" style="width:110px; height:73px; margin-top:8px; border:1px solid #40D70B" onmouseover="this.style.borderColor='#CCCCCC'" onmouseout="this.style.borderColor='#40D70B'" alt="<?php echo $this->escape($cjNews['title'])?>"/></a> 
                    </div>
                    <div class="cr">
                        <ul>
                            <li class="li1"><a href="<?php echo $this->baseUrl('/news/info-'.$cjNews['id'].'-1.html')?>" title="<?php echo $this->escape($cjNews['title'])?>" class="a24"><?php echo $this->substr($this->escape($cjNews['title']), 30)?></a></li>
                            <li class="li2">　　<?php echo trim($this->substr($this->escape($cjNews['uncontent']), 85))?><a href="<?php echo $this->baseUrl('/news/info-'.$cjNews['id'].'-1.html')?>" class="a3">&lt;详细&gt;</a></li>
                        </ul>
                    </div>
                    <div class="clear"></div>
                </div>
                    <?php else:?>
                <div class="content2">
                    ·<a href="<?php echo $this->baseUrl('/news/info-'.$cjNews['id'].'-1.html')?>" title="<?php echo $this->escape($cjNews['title'])?>"><?php echo $this->substr($this->escape($cjNews['title']), 58)?></a> 
                </div>    
                    <?php endif;?>
                <?php endforeach;?> 
            </div>
            <div class="clear"></div>
        </div> 
        <div class="cell_h"></div>
        <div class="p4">
            <div class="title">
                <img src="<?php echo $this->baseUrl('/img/title_mark1.gif')?>" style="position:absolute; left:8px; top:9px;" alt="图片新闻"/>　　图片新闻　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　<a href="<?php echo $this->baseUrl('/news/list-9-0-1.html')?>" class="a7">[更多]</a>
            </div>
            <div class="content">
                <ul>
                    <?php foreach ($this->imgNewses as $imgNews):?>
                    <li>
                        <a href="<?php echo $this->baseUrl('/news/info-'.$imgNews['id'].'-1.html')?>"><img src="<?php echo $this->baseUrl('/upfile/file/'.$imgNews['imagename'])?>" style="width:120px; height:80px; margin-top:10px; border:1px solid #40D70B" onmouseover="this.style.borderColor='#CCCCCC'" onmouseout="this.style.borderColor='#40D70B'" alt="<?php echo $this->escape($imgNews['title'])?>"/></a>
                        <br/><a href="<?php echo $this->baseUrl('/news/info-'.$imgNews['id'].'-1.html')?>" title="<?php echo $this->escape($imgNews['title'])?>" class="a24"><?php echo $this->substr($this->escape($imgNews['title']), 25)?></a>
                    </li>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>      
    </div>
    <div class="right">
        <div class="p1">
            <div class="title">
                <img src="<?php echo $this->baseUrl('/img/title_mark1.gif')?>" style="position:absolute; left:8px; top:9px;" alt="站内新闻"/>　　站内新闻　　　　　　　　　　　　　<a href="<?php echo $this->baseUrl('/news/list-0-0-1.html')?>" class="a7">[更多]</a>
            </div>
            <div class="content">
                <ul>
                    <?php foreach ($this->siteNewses as $siteNews):?>
                    <li>·<a href="<?php echo $this->baseUrl('/news/info-'.$siteNews['id'].'-1.html')?>" title="<?php echo $this->escape($siteNews['title'])?>"><?php echo $this->substr($this->escape($siteNews['title']), 50)?></a></li>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
        <div class="cell_h"></div>
        <div style="margin-left:0px; margin-right:0px; height:80px; background-color:#CCCCCC;">
        
        </div>
        <div class="cell_h"></div>
        <div class="p2">
            <div class="title">
                <img src="<?php echo $this->baseUrl('/img/title_mark1.gif')?>" style="position:absolute; left:8px; top:9px;" alt="高端访谈"/>　　高端访谈　　　　　　　　　　　　　<a href="<?php echo $this->baseUrl('/news/list-2-0-1.html')?>" class="a7">[更多]</a>
            </div>
            <?php foreach ($this->heighPersonNewses as $key => $heighPersonNews):?>
                <?php if($key == 0):?>
            <div class="content1">
                <div class="cl">
                    <a href="<?php echo $this->baseUrl('/news/info-'.$heighPersonNews['id'].'-1.html')?>"><img src="<?php echo $this->baseUrl('/upfile/file/'.$heighPersonNews['imagename'])?>" style="width:90px; height:60px; margin-top:15px; border:1px solid #40D70B" onmouseover="this.style.borderColor='#CCCCCC'" onmouseout="this.style.borderColor='#40D70B'" alt="<?php echo $this->escape($heighPersonNews['title'])?>"/></a> 
                </div>
                <div class="cr">
                    <ul>
                        <li class="li1"><a href="<?php echo $this->baseUrl('/news/info-'.$heighPersonNews['id'].'-1.html')?>" title="<?php echo $this->escape($heighPersonNews['title'])?>" class="a24"><?php echo $this->substr($this->escape($heighPersonNews['title']), 30)?></a></li>
                        <li class="li2">　　<?php echo trim($this->substr($this->escape($heighPersonNews['uncontent']), 75))?><a href="<?php echo $this->baseUrl('/news/info-'.$heighPersonNews['id'].'-1.html')?>" class="a3">&lt;详细&gt;</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
                <?php else:?>
            <div class="content2">
                ·<a href="<?php echo $this->baseUrl('/news/info-'.$heighPersonNews['id'].'-1.html')?>" title="<?php echo $this->escape($heighPersonNews['title'])?>"><?php echo $this->substr($this->escape($heighPersonNews['title']), 50)?></a> 
            </div>    
                <?php endif;?>
            <?php endforeach;?>     
        </div>
        <div class="cell_h"></div>
        <div class="p3">
            <div class="title">
                <img src="<?php echo $this->baseUrl('/img/title_mark1.gif')?>" style="position:absolute; left:8px; top:9px;" alt="综合资讯"/>　　综合资讯　　　　　　　　　　　　　<a href="<?php echo $this->baseUrl('/news/list-10-0-1.html')?>" class="a7">[更多]</a>
            </div>  
            <div class="content">
                <ul>
                    <?php foreach ($this->zhNewses as $key => $zhNews):?>
                    <li>
                       ·<a href="<?php echo $this->baseUrl('/news/info-'.$zhNews['id'].'-1.html')?>" title="<?php echo $this->escape($zhNews['title'])?>"><?php echo $this->substr($this->escape($zhNews['title']), 50)?></a> 
                    </li>
                    <?php endforeach;?>   
                </ul>
            </div>
        </div>  
    </div>
    <div class="clear"></div>
</div>