<style type="text/css">
    .default_header_logo                       {width:960px; height:80px; clear:both;}
    .default_header_logo .left                 {width:300px; height:80px; text-align:left; float:left;}
    .default_header_logo .right                {width:650px; height:80px; float:right;}
    .default_header_nav1                       {width:960px; height:29px; clear:both;}   
    .default_header_nav1 .li1                  {width:78px; height:29px; line-height:29px; font-weight:bold; background:url(<?php echo $this->baseUrl('/img/default_dh_btn2.gif')?>); margin-right:6px; float:left;}
    .default_header_nav2                       {width:960px; height:34px; background:url(<?php echo $this->baseUrl('/img/default_dh_center_center.gif')?>); clear:both;}
    .default_header_nav2 .left                 {width:2px; height:34px; font-size:0px; background:url(<?php echo $this->baseUrl('/img/default_dh_center_left.gif')?>); float:left;}
    .default_header_nav2 .center               {height:34px; line-height:34px; text-align:left; font-size:14px; color:#FFFFFF; float:left;}
    .default_header_nav2 .right                {width:2px; height:34px; font-size:0px; background:url(<?php echo $this->baseUrl('/img/default_dh_center_right.gif')?>); float:right;}

</style>


<div class="default_header_logo">
    <div class="left">
            <a href="#"><img src="<?php echo $this->baseUrl('/img/logo.jpg')?>" style="margin-top:13px; border:0px;"/></a>
    </div>
    <div class="right">
        <div style="width:100%; height:18px; clear:both;"></div>
        <form name="form_search" id="form_search" method="post" action="" style="padding:0px; margin:0px;">
        <div style="width:100%; height:35px; background:url(<?php echo $this->baseUrl('/img/top_search_center.jpg')?>); clear:both;">
            <div style="width:10px; height:35px; background:url(<?php echo $this->baseUrl('/img/top_search_left.jpg')?>); float:left;"></div>
            <div style="position:relative; width:564px; height:35px; float:left;">
			    <input type="text" name="keyWord" id="keyWord" class="input" style="width:340px; height:18px; line-height:18px; font-size:14px; position:absolute; top:7px; left:5px; background:url(<?php echo $this->baseUrl('/img/search_bg.gif')?>);" onclick="this.style.backgroundColor='#FFFFFF'; this.style.background='url(<?php echo $this->baseUrl('/img/search_bg_white.gif')?>)'">
				<input type="image" src="<?php echo $this->baseUrl('/img/default_searchbutton1.jpg') ?>" style="position:absolute; top:7px; left:365px;" />
				<img src="<?php echo $this->baseUrl('/img/mark8.gif') ?>" style="position:absolute; top:6px; left:440px;" />
            </div>            
            <div style="width:10px; height:35px; background:url(<?php echo $this->baseUrl('/img/top_search_right.jpg')?>); float:right;"></div>
        </div>
        </form>
        <div style="width:100%; height:25px; line-height:25px; text-align:left; color:#24880A; clear:both;">
        热门关键字：<a href="#" class="a24">PHP</a>　<a href="#" class="a24">JSP</a>　<a href="#" class="a24">.net</a>　<a href="#" class="a24">Ajax</a>　<a href="#" class="a24">素材</a>　<a href="#" class="a24">源码</a>　<a href="#" class="a24">模板</a>　<a href="#" class="a24">框架</a>
        </div>
    </div>
</div>
<div class="default_header_nav1">
    <ul>
        <li class="li1"><a href="#" class="a2">首　页</a></li>
        <li class="li1"><a href="#" class="a2">站内新闻</a></li>
        <li class="li1"><a href="#" class="a2">IT人物</a></li>
        <li class="li1"><a href="#" class="a2">高端访谈</a></li>
        <li class="li1"><a href="#" class="a2">产品快讯</a></li>
        <li class="li1"><a href="#" class="a2">企业动态</a></li>
        <li class="li1"><a href="#" class="a2">互联网</a></li>
        <li class="li1"><a href="#" class="a2">游戏资讯</a></li>
        <li class="li1"><a href="#" class="a2">广告传媒</a></li>
        <li class="li1"><a href="#" class="a2">财经报道</a></li>
        <li class="li1"><a href="#" class="a2">图片新闻</a></li>
    </ul>
</div>
<div class="default_header_nav2">
    <div class="left"></div>
    <div class="center">
　当前位置：通过zend_layout设计网站布局
    </div>
    <div class="right"></div>
</div>
<div class="cell_h"></div>