<style type="text/css">
    .default-footer-line                     {width:960px; height:1px; line-height:1px; font-size:1px; padding:0px; border-top:1px solid #BDE2FD; clear:both; } 
    .default-footer-dh                       {width:960px; height:24px; line-height:24px; color:#004A9D; background-color:#EDF8FA; clear:both; }
    .default-footer-bq                       {width:960px; height:40px; line-height:20px; color:#333333; clear:both; }
    .default-footer-netimg                   {width:960px; clear:both;}
    .default-footer-netimg img               {border:1px solid #EBEBEB; margin-left:3px; margin-right:3px; }   
    
</style>
<div class="cell_h"></div>
<div class="default-footer-line"></div>
<div class="default-footer-dh">
    <a href="#" class="a3">关于我们</a>　|　<a href="#" class="a3">广告招商</a>　|　<a href="#" class="a3">举报中心</a>　|　<a href="#" class="a3">联系方式</a>　|　<a href="#" class="a3">版权声明</a>　|　<a href="#" class="a3">客户服务</a>　|　<a href="#" class="a3">会员注册</a> 
</div>
<div class="cell_h"></div>
<div class="default-footer-bq">
E-mail：mingrisoft@mingrisoft.com　电话：0431-8497****　技术群：800****　吉ICP备0312***号<br/>
Copyright　(C)　明日IT新闻网　2009-2010,　All　Rights　Reserved
</div>
<div class="cell_h"></div>
<div class="default-footer-netimg">
    <img src="<?php echo $this->baseUrl('/img/mark_icp.gif')?>" /><img src="<?php echo $this->baseUrl('/img/mark_hyggwl.gif')?>" /><img src="<?php echo $this->baseUrl('/img/mark_blxxjb.gif')?>" /><img src="<?php echo $this->baseUrl('/img/mark_wl110.gif')?>" />
</div>
<div class="cell_h"></div>