<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>更新数据</title>
<link href="<?php echo $this->baseUrl('css/style.css');?>" rel="stylesheet" type="text/css" />
</head>
<body>
<table width="600" border="1" cellpadding="1" cellspacing="1" bordercolor="#FFFFFF" bgcolor="#336600">

  <tr>
      <td height="30" align="center" bgcolor="#FFFFFF"><?php echo $this->update; ?></td>
  </tr>
  <tr>
                        <td height="30" align="center" bgcolor="#FFFFFF"><table width="300" border="0" cellpadding="0" cellspacing="0">
                        
                        <tr>
                            <td><a href="<?php echo $this->baseUrl('index/index');?>">添加数据</a></td>
                            <td><a href="<?php echo $this->baseUrl('index/update');?>">更新</a></td>
                            <td><a href="<?php echo $this->baseUrl('index/delete');?>">删除</a></td>
                            <td height="28"><a href="<?php echo $this->baseUrl('index/fetch');?>">查看</a></td>
                        </tr>
        </table></td>
    </tr>
                </table>
                    

</body>
</html>
