<script src="{util->baseUrl}/js/jquery.js"></script>  
<script language="javascript" >
$(document).ready(
	    function(){ldelim}
	    	$("#bigtypeid").change(function(){ldelim}
	            $.get("{util->baseUrl}/getstype.php?stid="+$("#bigtypeid").val(), null, function(data){ldelim}
	            	$("#smalltypeid").empty();
	            	$("#smalltypeid").append(data);
	          {rdelim});
	        {rdelim}); 
	        
		    $("#smalltypeid").change(function(){ldelim}
	            $.get("{util->baseUrl}/getbook.php?bid="+$("#smalltypeid").val(), null, function(data){ldelim}
	            	$("#bookid").empty();
	            	$("#bookid").append(data);
	          {rdelim});
	       {rdelim}); 	
	    {rdelim}
	);

</script> 

<div style="width:98%; height:25px; text-align:left"><input type="button" value="添加图书试读信息"  onclick="window.location.href='{util->baseUrl}/admin-read.php'" />&nbsp;&nbsp;<input type="button" value="浏览图书试读信息" onclick="window.location.href='{util->baseUrl}/admin-listread.php'"/></div>    
    <div style="width:98%;  border:1px solid #006D84">
        <div style="width:100%; height:25px; border:1px solid #FFFFFF; background-color:#4995A8; text-align:left; padding-top:5px; padding-left:20px; color:#FFFFFF">
            <li style="display:inline; float:left"><strong>浏览图书试读信息</strong></li>
        </div>
        
        <div style="width:100%; background-color:#CCCCCC">
            <div style="width: 50%; height:16px; float:left; padding-top:3px; border-right:1px solid #FFFFFF">
               图书名称
            </div>            
            <div style="width: 20%; height:16px; float:left; padding-top:3px; border-right:1px solid #FFFFFF">
               试读文件名
            </div>       
             <div style="width:20%; height:16px; float:left; padding-top:3px; border-right:1px solid #FFFFFF">
               添加时间
            </div>  
                         
             <div style="width:10%; height:16px; float:left; padding-top:3px">
               操作
            </div>       
        </div>  
        {section name=rID loop=$reads.data}
        <div style="width:100%; border-top:1px solid #006D84">
            <div style="width:50%; height:20px; float:left; padding-top:4px; border-right:1px solid #006D84; text-align:left; padding-left:20px">
               {util->unHtml p=$reads.data[rID].bookname}
            </div>            

            <div style="width:20%; height:20px; float:left; padding-top:4px; border-right:1px solid #006D84; text-align:left; padding-left:20px">
               {util->unHtml p=$reads.data[rID].filename}
            </div>    


            <div style="width:20%; height:20px; float:left; padding-top:4px; border-right:1px solid #006D84">
               {$reads.data[rID].addtime}
            </div>  
                         
            <div style="width:10%; height:20px; float:left; padding-top:2px">
                <a href="{util->baseUrl}/admin-listread.php?f=edit&id={$reads.data[rID].id}"><img src="{util->baseUrl}/img/edit.gif" border="0"/></a>&nbsp;<a href="javascript:if(window.confirm('确定删除？')==true){ldelim}window.location.href='{util->baseUrl}/admin-listread.php?f=del&id={$reads.data[rID].id}';{rdelim}"><img src="{util->baseUrl}/img/del.gif" border="0"/></a>
            </div>       
        </div>          
        {/section}
    </div>

    {if $isShow == "T"}
    <br/>
    <div style="width:98%;  border:1px solid #006D84">
        <div style="width:100%; height:25px; border:1px solid #FFFFFF; background-color:#4995A8; text-align:left; padding-top:5px; padding-left:20px; color:#FFFFFF">
            <li style="display:inline; float:left"><strong>更改图书试读信息</strong></li>
        </div>
        
        <div style="width:100%; text-align:left; padding-top:5px; padding-left:20px; padding-left:70px">
         
          <form name="form_read" method="post" action="{util->baseUrl}/admin-listread.php" onsubmit="return chkInputRead(this)">
            <div style="width:100%; text-align:left; padding-top:5px; padding-left:50px">
              类别：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<select id="bigtypeid" name="bigtypeid">
             <option value='' selected>-请选择-</option>
             {html_options options = $arrayBtypeOption}      
       </select>  
&nbsp;<select name="smalltypeid" id="smalltypeid">
             <option value='' selected>-请选择-</option> 
       </select> <br /><br />
      图书名称：&nbsp;&nbsp;<select name="bookid" id="bookid">
             <option value=''>-请选择-</option>
             <option value='{$read[0].id}' selected>{$read[0].bookname}</option> 
       </select> <br /><br />     
            
            
                  试读文件名：<input type="text" name="filename" size="30" class="input" value="{$read[0].filename}"/><br /><br /> 
                <input type="hidden" name="f" value="edit" />
                <input type="hidden" name="id" value="{$read[0].id}" />
                <input type="submit" value="更改" />&nbsp;&nbsp;<input type="reset" value="重置" />
            </div> 
            </form>  
        
    
        </div>    
    </div>
    {/if}
    <br />
    <div style="width:98%; height:25px; border-top:1px dotted #CCCCCC; padding-top:5px; text-align:left; padding-left:20px; background-color:#FFFBE5">
          {if $reads.countRs > 0}   
          <li style="display:inline; padding-left:20px">{$nowtype}共&nbsp;{$reads.countRs}&nbsp;本&nbsp;&nbsp;每页显示&nbsp;{$reads.pageSize}&nbsp;本&nbsp;&nbsp;第&nbsp;{$reads.page}&nbsp;页/共&nbsp;{$reads.countPage}&nbsp;页&nbsp;&nbsp;&nbsp;&nbsp;
              <a href="{util->baseUrl}/admin-listread.php?page={$reads.first}" class="a1">首页</a>&nbsp;
              <a href="{util->baseUrl}/admin-listread.php?page={$reads.previous}" class="a1">上一页</a>&nbsp;
              <a href="{util->baseUrl}/admin-listread.php?page={$reads.next}" class="a1">下一页</a>&nbsp;
              <a href="{util->baseUrl}/admin-listread.php?page={$reads.last}" class="a1">尾页</a>
          </li>           
          {/if}
    </div>      
    
    