    <div style="width:98%; height:25px; text-align:left"><input type="button" value="添加出版社类别信息"  onclick="window.location.href='{util->baseUrl}/admin-pub.php'" />&nbsp;&nbsp;<input type="button" value="浏览出版社类别信息" onclick="window.location.href='{util->baseUrl}/admin-listpub.php'"/></div>    
    <div style="width:98%;  border:1px solid #006D84">
        <div style="width:100%; height:25px; border:1px solid #FFFFFF; background-color:#4995A8; text-align:left; padding-top:5px; padding-left:20px; color:#FFFFFF">
            <li style="display:inline; float:left"><strong>添加出版社类别信息</strong></li>
        </div>
        
        <div style="width:100%; text-align:left; padding-top:5px; padding-left:20px; padding-left:70px">
         
          <form name="form_pub" method="post" action="{util->baseUrl}/admin-pub.php" onsubmit="return chkInputPub(this)" enctype="multipart/form-data">
            <div style="width:100%; text-align:left; padding-top:5px; padding-left:50px">
                  出版社名称：&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="pubname" size="30" class="input"/><br /><br /> 
       出版社logo图片：<input type="file" name="pubimg" size="30" class="input" /> <br /><br />     
                <input type="submit" value="添加" />&nbsp;&nbsp;<input type="reset" value="重置" />
            </div> 
            </form>  
        
    
        </div>    
    </div>