    <div style="width:98%; height:25px; text-align:left"><input type="button" value="添加图书小类信息"  onclick="window.location.href='{util->baseUrl}/admin-smalltype.php'" />&nbsp;&nbsp;<input type="button" value="浏览图书小类信息" onclick="window.location.href='{util->baseUrl}/admin-listsmalltype.php'"/></div>    
     <br />
    {if $isShow == "T"}
    <div style="width:98%;  border:1px solid #006D84">
        <div style="width:100%; height:25px; border:1px solid #FFFFFF; background-color:#4995A8; text-align:left; padding-top:5px; padding-left:20px; color:#FFFFFF">
            <li style="display:inline; float:left"><strong>更改图书小类信息</strong></li>
        </div>
        
        <div style="width:100%; text-align:left; padding-top:5px; padding-left:20px; padding-left:70px">
         
          <form name="form_editsmalltype" method="post" action="{util->baseUrl}/admin-listsmalltype.php" onsubmit="return chkInputSmalltype(this)">
            <div style="width:100%; text-align:left; padding-top:5px; padding-left:50px">
                  小类名称：<input type="text" name="typename" size="30" class="input" value="{$smalltype[0].typename}"/><br /><br />
                  <input type="hidden" name="f" value="edit" /> 
                         所属大类：<select name="bigtypeid">
                     <option value="">-请选择-</option>
                     {html_options options = $arrayBtypeOption selected = $smalltype[0].bigtypeid}
                  </select><br /><br />            
                  <input type="hidden" name="id" value="{$smalltype[0].id}" />
                   
                <input type="submit" value="更改" />&nbsp;&nbsp;<input type="reset" value="重置" />
            </div> 
            </form>  
        
    
        </div>    
    </div>
    <br />
    {/if}  
   
   
    <div style="width:98%;  border:1px solid #006D84">
        <div style="width:100%; height:25px; border:1px solid #FFFFFF; background-color:#4995A8; text-align:left; padding-top:5px; padding-left:20px; color:#FFFFFF">
            <li style="display:inline; float:left"><strong>浏览图书小类信息</strong></li>
        </div>
        
        <div style="width:100%; background-color:#CCCCCC">
            <div style="width:50%; height:16px; float:left; padding-top:3px; border-right:1px solid #FFFFFF">
               类别名称
            </div>  
                      
             <div style="width:20%; height:16px; float:left; padding-top:3px; border-right:1px solid #FFFFFF">
               所属大类
            </div>
             
             <div style="width:20%; height:16px; float:left; padding-top:3px; border-right:1px solid #FFFFFF">
               添加时间
            </div>  
                         
             <div style="width:10%; height:16px; float:left; padding-top:3px">
               操作
            </div>       
        </div>  
        {section name=tID loop=$smalltypes}
        <div style="width:100%; border-top:1px solid #006D84">
            <div style="width:50%; height:20px; float:left; padding-top:4px; border-right:1px solid #006D84; text-align:left; padding-left:20px">
               {util->unHtml p=$smalltypes[tID].stypename}
            </div> 
                       
            <div style="width:20%; height:20px; float:left; padding-top:4px; border-right:1px solid #006D84; padding-left:10px; text-align:left">
               {util->unHtml p=$smalltypes[tID].btypename}
            </div> 
            
            <div style="width:20%; height:20px; float:left; padding-top:4px; border-right:1px solid #006D84">
               {util->unHtml p=$smalltypes[tID].addtime}
            </div>  
                         
            <div style="width:10%; height:20px; float:left; padding-top:2px">
                <a href="{util->baseUrl}/admin-listsmalltype.php?f=edit&id={$smalltypes[tID].id}"><img src="{util->baseUrl}/img/edit.gif" border="0"/></a>&nbsp;<a href="javascript:if(window.confirm('确定删除？')==true){ldelim}window.location.href='{util->baseUrl}/admin-listsmalltype.php?f=del&id={$smalltypes[tID].id}';{rdelim}"><img src="{util->baseUrl}/img/del.gif" border="0"/></a>
            </div>       
        </div>          
        {/section}
    </div>

    <br />
    