    
    <div style="width:98%;  border:1px solid #006D84">
        <div style="width:100%; height:25px; border:1px solid #FFFFFF; background-color:#4995A8; text-align:left; padding-top:5px; padding-left:20px; color:#FFFFFF">
            <li style="display:inline; float:left"><strong>修改管理员密码</strong></li>
        </div>
        
        <div style="width:100%; height:120px; text-align:left; padding-top:5px; padding-left:20px; padding-left:70px">

          <form name="form_adminpwd" method="post" action="{util->baseUrl}/admin-changepwd.php" onsubmit="return chkChangePwd(this)">
            <div style="width:100%; text-align:left; padding-top:5px; padding-left:50px">
                  原密码：&nbsp;&nbsp;&nbsp;&nbsp;<input type="password" name="oldpwd" size="30" class="input"/><br /><br />
                   新密码：&nbsp;&nbsp;&nbsp;&nbsp;<input type="password" name="pwd1" size="30" class="input"/><br /><br /> 
                   确认新密码：<input type="password" name="pwd2" size="30" class="input"/><br /><br />             
                  <input type="submit" value="更改" />&nbsp;&nbsp;<input type="reset" value="重置" />
            </div> 
            </form>  
    
        </div>    
    </div>