    div style="width:98%; height:25px; text-align:left"><input type="button" value="添加明日图书排行信息"  onclick="window.location.href='{util->baseUrl}/admin-mrbookph.php'" />&nbsp;&nbsp;<input type="button" value="浏览明日图书排行信息" onclick="window.location.href='{util->baseUrl}/admin-listmrbookph.php'"/></div>    
    <div style="width:98%;  border:1px solid #006D84">
        <div style="width:100%; height:25px; border:1px solid #FFFFFF; background-color:#4995A8; text-align:left; padding-top:5px; padding-left:20px; color:#FFFFFF">
            <li style="display:inline; float:left"><strong>浏览图书排行信息</strong></li>
        </div>
        
        <div style="width:100%; background-color:#CCCCCC">
            <div style="width:70%; height:16px; float:left; padding-top:3px; border-right:1px solid #FFFFFF">
               主题
            </div>            

             <div style="width:20%; height:16px; float:left; padding-top:3px; border-right:1px solid #FFFFFF">
               添加时间
            </div>  
                         
             <div style="width:10%; height:16px; float:left; padding-top:3px">
               操作
            </div>       
        </div>  
        {section name=tID loop=$tells.data}
        <div style="width:100%; border-top:1px solid #006D84">
            <div style="width:70%; height:20px; float:left; padding-top:4px; border-right:1px solid #006D84; text-align:left; padding-left:20px">
               {util->unHtml p=$tells.data[tID].title}
            </div>            

            <div style="width:20%; height:20px; float:left; padding-top:4px; border-right:1px solid #006D84">
               {$tells.data[tID].addtime}
            </div>  
                         
            <div style="width:10%; height:20px; float:left; padding-top:2px">
                <a href="{util->baseUrl}/admin-mrbookph.php?f=edit&id={$tells.data[tID].id}"><img src="{util->baseUrl}/img/edit.gif" border="0"/></a>&nbsp;<a href="javascript:if(window.confirm('确定删除？')==true){ldelim}window.location.href='{util->baseUrl}/admin-listmrbookph.php?f=del&id={$tells.data[tID].id}';{rdelim}"><img src="{util->baseUrl}/img/del.gif" border="0"/></a>
            </div>       
        </div>          
        {/section}
    </div>
    
    
    <br />
    <div style="width:98%; height:25px; border-top:1px dotted #CCCCCC; padding-top:5px; text-align:left; padding-left:20px; background-color:#FFFBE5">
          {if $tells.countRs > 0}   
          <li style="display:inline; padding-left:20px">{$nowtype}共&nbsp;{$tells.countRs}&nbsp;条&nbsp;&nbsp;每页显示&nbsp;{$tells.pageSize}&nbsp;条&nbsp;&nbsp;第&nbsp;{$tells.page}&nbsp;页/共&nbsp;{$tells.countPage}&nbsp;页&nbsp;&nbsp;&nbsp;&nbsp;
              <a href="{util->baseUrl}/admin-listmrbookph.php?page={$tells.first}" class="a1">首页</a>&nbsp;
              <a href="{util->baseUrl}/admin-listmrbookph.php?page={$tells.previous}" class="a1">上一页</a>&nbsp;
              <a href="{util->baseUrl}/admin-listmrbookph.php?page={$tells.next}" class="a1">下一页</a>&nbsp;
              <a href="{util->baseUrl}/admin-listmrbookph.php?page={$tells.last}" class="a1">尾页</a>
          </li>           
          {/if}
    </div>   

    