    <div style="width:98%; height:25px; text-align:left"><input type="button" value="添加图书小类信息"  onclick="window.location.href='{util->baseUrl}/admin-smalltype.php'" />&nbsp;&nbsp;<input type="button" value="浏览图书小类信息" onclick="window.location.href='{util->baseUrl}/admin-listsmalltype.php'"/></div>    
    <div style="width:98%;  border:1px solid #006D84">
        <div style="width:100%; height:25px; border:1px solid #FFFFFF; background-color:#4995A8; text-align:left; padding-top:5px; padding-left:20px; color:#FFFFFF">
            <li style="display:inline; float:left"><strong>添加图书小类信息</strong></li>
        </div>
        
        <div style="width:100%; text-align:left; padding-top:5px; padding-left:20px; padding-left:70px">
         
          <form name="form_addsmalltype" method="post" action="{util->baseUrl}/admin-smalltype.php" onsubmit="return chkInputSmalltype(this)">
            <div style="width:100%; text-align:left; padding-top:5px; padding-left:50px">
                  小类名称：<input type="text" name="typename" size="30" class="input"/><br /><br /> 
                  所属大类：<select name="bigtypeid">
                     <option value="">-请选择-</option>
                     {html_options options = $arrayBtypeOption}
                  </select><br /><br /> 
                <input type="submit" value="添加" />&nbsp;&nbsp;<input type="reset" value="重置" />
            </div> 
            </form>  
        
    
        </div>    
    </div>