<html>
    <head>
        <title>明日网上书店管理中心 - 左侧导航</title>
        <meta http-equiv="Content-Type" content="text/html; charset=gbk" />
        <link rel="stylesheet" type="text/css" href="{util->baseUrl}/css/style.css" />
    </head>
    <script src="{util->baseUrl}/js/adminfun.js"></script>
    <body style="background-color:#FFFFFF; padding-top:10px" scroll="auto">
    <div style="width:98%; height:50px; border:1px solid #006D84">
        <div style="width:100%; height:25px; border:1px solid #FFFFFF; background-color:#4995A8; text-align:left; padding-top:5px; padding-left:20px; color:#FFFFFF">
            <li style="display:inline; float:left"><strong>管理员：{$smarty.session.anc}</strong></li>
            <li style="display:inline; float:right;"><a href="{util->baseUrl}/admin-changepwd.php" class="a2">更改密码</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{util->baseUrl}/admin-logout.php" class="a2" target="_parent">退出登录</a>&nbsp;&nbsp;</li>
        </div>
        <div style="width:100%; height:25px; text-align:left; padding-top:5px; padding-left:20px">
        当前位置：明日网上书店&nbsp;>>&nbsp;管理中心&nbsp;>>&nbsp;{$position}  
        </div>        
    </div>
    <div style="width:50px; height:7px; font-size:0px"></div>