    <div style="width:98%; height:25px; text-align:left"><input type="button" value="添加图书大类信息"  onclick="window.location.href='{util->baseUrl}/admin-bigtype.php'" />&nbsp;&nbsp;<input type="button" value="浏览图书大类信息" onclick="window.location.href='{util->baseUrl}/admin-listbigtype.php'"/></div>    
    <div style="width:98%;  border:1px solid #006D84">
        <div style="width:100%; height:25px; border:1px solid #FFFFFF; background-color:#4995A8; text-align:left; padding-top:5px; padding-left:20px; color:#FFFFFF">
            <li style="display:inline; float:left"><strong>浏览图书大类信息</strong></li>
        </div>
        
        <div style="width:100%; background-color:#CCCCCC">
            <div style="width:70%; height:16px; float:left; padding-top:3px; border-right:1px solid #FFFFFF">
               类别名称
            </div>            

             <div style="width:20%; height:16px; float:left; padding-top:3px; border-right:1px solid #FFFFFF">
               添加时间
            </div>  
                         
             <div style="width:10%; height:16px; float:left; padding-top:3px">
               操作
            </div>       
        </div>  
        {section name=tID loop=$bigtypes}
        <div style="width:100%; border-top:1px solid #006D84">
            <div style="width:70%; height:20px; float:left; padding-top:4px; border-right:1px solid #006D84; text-align:left; padding-left:20px">
               {util->unHtml p=$bigtypes[tID].typename}
            </div>            

            <div style="width:20%; height:20px; float:left; padding-top:4px; border-right:1px solid #006D84">
               {util->unHtml p=$bigtypes[tID].addtime}
            </div>  
                         
            <div style="width:10%; height:20px; float:left; padding-top:2px">
                <a href="{util->baseUrl}/admin-listbigtype.php?f=edit&id={$bigtypes[tID].id}"><img src="{util->baseUrl}/img/edit.gif" border="0"/></a>&nbsp;<a href="javascript:if(window.confirm('确定删除？')==true){ldelim}window.location.href='{util->baseUrl}/admin-listbigtype.php?f=del&id={$bigtypes[tID].id}';{rdelim}"><img src="{util->baseUrl}/img/del.gif" border="0"/></a>
            </div>       
        </div>          
        {/section}
    </div>
    <br />
    {if $isShow == "T"}
    <div style="width:98%;  border:1px solid #006D84">
        <div style="width:100%; height:25px; border:1px solid #FFFFFF; background-color:#4995A8; text-align:left; padding-top:5px; padding-left:20px; color:#FFFFFF">
            <li style="display:inline; float:left"><strong>更改图书大类信息</strong></li>
        </div>
        
        <div style="width:100%; text-align:left; padding-top:5px; padding-left:20px; padding-left:70px">
         
          <form name="form_editbigtype" method="post" action="{util->baseUrl}/admin-listbigtype.php" onsubmit="return chkInputBigtype(this)">
            <div style="width:100%; text-align:left; padding-top:5px; padding-left:50px">
                  大类名称：<input type="text" name="typename" size="30" class="input" value="{$bigtype[0].typename}"/><br /><br />
                  <input type="hidden" name="f" value="edit" /> 
                  <input type="hidden" name="id" value="{$bigtype[0].id}" /> 
                <input type="submit" value="更改" />&nbsp;&nbsp;<input type="reset" value="重置" />
            </div> 
            </form>  
        
    
        </div>    
    </div>
    {/if}
    <br />
    