<div style="width:950px; background-color:#FFFFFF">
    <div style="width:930px">
        <div style="width:200px; float:left">
            <div style="width:200px; height:30px">
                <div style="width:6px; height:30px; background:url({util->baseUrl}/img/dg_left.gif); float:left"></div>
                <div style="width:188px; height:30px; background:url({util->baseUrl}/img/dg_center.gif); float:left; padding-top:5px">
                    <div style="width:45px; height:25px; float:left; padding-top:5px; {if $cctype == 1}background:url({util->baseUrl}/img/dg_button_bg.gif){/if}"><a href="{util->baseUrl}/pub-1.html" class="{if $cctype == 1}a2{else}a1{/if}"><strong>全部</strong></a></div>
                    
                    <div style="width:45px; height:25px;  float:left; padding-top:5px; {if $cctype == 2}background:url({util->baseUrl}/img/dg_button_bg.gif){/if}"><a href="{util->baseUrl}/pub-2.html" class="{if $cctype == 2}a2{else}a1{/if}"><strong>初级</strong></a></div>
                
                    <div style="width:45px; height:25px;  float:left; padding-top:5px; {if $cctype == 3}background:url({util->baseUrl}/img/dg_button_bg.gif){/if}"><a href="{util->baseUrl}/pub-3.html" class="{if $cctype == 3}a2{else}a1{/if}"><strong>中级</strong></a></div>
                    
                    <div style="width:45px; height:25px;  float:left; padding-top:5px; {if $cctype == 4}background:url({util->baseUrl}/img/dg_button_bg.gif){/if}"><a href="{util->baseUrl}/pub-4.html" class="{if $cctype == 4}a2{else}a1{/if}"><strong>高级</strong></a></div>
                </div>    
                <div style="width:6px; height:30px; background:url({util->baseUrl}/img/dg_right.gif); float:right"></div>        
            </div>
            <div style="width:200px; background-color:#FDFBED; border-left:1px solid #FF6700; border-right:1px solid #FF6700; border-bottom:1px solid #FF6700">
                <div style="width:100%; height:22px; border-bottom:1px dotted #CCCCCC; background-color:#F7F7F7; padding-top:5px; text-align:left; padding-left:15px">
                                                     当前导航：
                    {if $cctype == '1'}
                                                                全部图书导航
                    {elseif $cctype == '2'}
                                                                  初级入门类图书
                    {elseif $cctype == '3'}
                                                                  提高必备类图书
                    {elseif $cctype == '4'}
                                                                  高级导向类图书
                    {/if}
                </div>
                <div style="width:50px; height:10px; font-size:0px"></div>
                {section name=bID loop=$bigtypes}
                <div style="width:195px">
                    <div style="width:100%; height:25px; text-align:left; padding-left:6px; padding-top:5px; color:#990000">
                        ·&nbsp;{util->unHtml p=$bigtypes[bID].typename}
                    </div>
                
                    <div style="width:100%">
                        {section name=sID loop=$smalltypes}
                        {if $bigtypes[bID].id == $smalltypes[sID].bigtypeid}
                        <div style="width:49%; height:18px; float:left; text-align:left; padding-left:12px">
                            ·&nbsp;<a href="{util->baseUrl}/listbook-{$smalltypes[sID].id}-{if $cctype==1}1{elseif $cctype==2}2{elseif $cctype==3}3{elseif $cctype==4}4{/if}.html" class="a4">{util->unHtml p=$smalltypes[sID].typename}</a>
                        </div>
                        {/if}    
                        {/section}   
                    </div>
                
                </div>
                {/section}
                <div style="width:50px; height:10px; font-size:0px"></div>
            </div>
            
            <div style="width:50px; height:7px; font-size:0px"></div>        
      
        </div>
        <!-- 中间 -->
        
        <div style="width:700px; height:100%; float:right">
            <div style="width: 100%; height:30px; text-align:left; padding-top:6px; border-bottom:1px solid #CCCCCC">
                                         当前位置：明日网上书店&nbsp;>>&nbsp;按出版社名称查看图书
            </div>  
            <br />
            {section name=tID loop = $pubs.data}
            <div style="width:90%; height:25px; border-bottom:1px dotted #333333; padding-top:5px">
                <li style="display:inline; width:80%; float:left; text-align:left"><a href="{util->baseUrl}/pubbook-{$pubs.data[tID].id}.html" class="a1">·{util->unHtml p=$pubs.data[tID].pubname}</a></li>
                <li style="display:inline; width:20%; float:right; text-align:right">{util->msubstr p=$pubs.data[tID].addtime p1=0 p2=10}</li>
            </div>
            {/section}
            <br />
            
            <div style="width:88%; text-align:left">
                <li style="display:inline; padding-left:20px">共有出版社名称&nbsp;{$pubs.countRs}&nbsp;条&nbsp;&nbsp;每页显示&nbsp;{$pubs.pageSize}&nbsp;条&nbsp;&nbsp;第&nbsp;{$pubs.page}&nbsp;页/共&nbsp;{$pubs.countPage}&nbsp;页&nbsp;&nbsp;&nbsp;&nbsp;<a href="{util->baseUrl}/pub-{$pubs.first}-{$cctype}.html" class="a1">首页</a>&nbsp;
                <a href="{util->baseUrl}/pub-{$pubs.previous}-{$cctype}.html" class="a1">上一页</a>&nbsp;
                <a href="{util->baseUrl}/pub-{$pubs.next}-{$cctype}.html" class="a1">下一页</a>&nbsp;
                <a href="{util->baseUrl}/pub-{$pubs.last}-{$cctype}.html" class="a1">尾页</a>
                </li>  
            </div>
            
            
        </div>             
    </div>
</div>