
<div style="width:950px; background-color:#FFFFFF">
    <div style="width:930px; height:20px; background:url({util->baseUrl}/img/title4.gif); border-top:1px solid #CCCCCC; padding-top:3px; padding-left:20px; font-size:13px; text-align:left">
               您当前的位置：明日网上书店&nbsp;>>&nbsp;注册成功
    </div>
    <div style="width:930px; height:150px;">
       <div style="width:30%; height:100%; float:left; padding-top:20px; text-align:right">
           <img src="{util->baseUrl}/img/mark_success.gif" />
       </div>
       <div style="width:68%; height:100%; text-align:left; padding-top:40px; font-size:14px">
           恭喜！{$smarty.session.unc}&nbsp;您已经成功注册为明日网上书店的会员！<br /><br />
         [<a href="{util->baseUrl}/index.php" class="a1">返回首页</a>]&nbsp;&nbsp;[<a href="{util->baseUrl}/usercenter.html" class="a1">会员中心</a>]&nbsp;&nbsp;[<a href="{util->baseUrl}/logout.php" class="a1">退出登录</a>]  
       </div>       
    </div>    
</div>
       
