
<div style="width:950px; background-color:#FFFFFF">
    <div style="width:930px; height:20px; background:url({util->baseUrl}/img/title4.gif); border-top:1px solid #CCCCCC; padding-top:3px; padding-left:20px; font-size:13px; text-align:left">
               您当前的位置：明日网上书店&nbsp;>>&nbsp;{$nowtype}
    </div>
     {if $bookinfos.countRs > 0}
    <div style="width:930px; height:25px; border-top:1px dotted #CCCCCC; padding-top:5px; text-align:left; padding-left:20px; background-color:#FFFBE5">
         
          {if $stype == "simple"}
          <li style="display:inline; padding-left:20px">共查找到相关图书&nbsp;{$bookinfos.countRs}&nbsp;本&nbsp;&nbsp;每页显示&nbsp;{$bookinfos.pageSize}&nbsp;本&nbsp;&nbsp;第&nbsp;{$bookinfos.page}&nbsp;页/共&nbsp;{$bookinfos.countPage}&nbsp;页&nbsp;&nbsp;&nbsp;&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.first}-{$key}-simple.html" class="a1">首页</a>&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.previous}-{$key}-simple.html" class="a1">上一页</a>&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.next}-{$key}-simple.html" class="a1">下一页</a>&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.last}-{$key}-simple.html" class="a1">尾页</a>
          </li>  
          {elseif $stype == "adv"}
          <li style="display:inline; padding-left:20px">共查找到相关图书&nbsp;{$bookinfos.countRs}&nbsp;本&nbsp;&nbsp;每页显示&nbsp;{$bookinfos.pageSize}&nbsp;本&nbsp;&nbsp;第&nbsp;{$bookinfos.page}&nbsp;页/共&nbsp;{$bookinfos.countPage}&nbsp;页&nbsp;&nbsp;&nbsp;&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.first}-{$key}-{$writer}-{$fyear}-{$fmonth}-{$tyear}-{$tmonth}-{$pubid}-{$smalltypeid}-adv.html" class="a1">首页</a>&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.previous}-{$key}-{$writer}-{$fyear}-{$fmonth}-{$tyear}-{$tmonth}-{$pubid}-{$smalltypeid}-adv.html" class="a1">上一页</a>&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.next}-{$key}-{$writer}-{$fyear}-{$fmonth}-{$tyear}-{$tmonth}-{$pubid}-{$smalltypeid}-adv.html" class="a1">下一页</a>&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.last}-{$key}-{$writer}-{$fyear}-{$fmonth}-{$tyear}-{$tmonth}-{$pubid}-{$smalltypeid}-adv.html" class="a1">尾页</a>
          </li>                    
         
          {/if}
    </div> 
    {/if}
    {if $bookinfos.countRs > 0} 
    {section name=pbID loop=$bookinfos.data}
    <div style="width:930px">
        <br>
        <div style="width:100%; height:180px">
            <div style="width:20%; height:100%; float:left">
                <a href="{util->baseUrl}/bookinfo-{$bookinfos.data[pbID].id}.html"><img src="{$system[0].bookimgurl}/{$bookinfos.data[pbID].bookimg}" width="110" height="150" style="border:1px solid #123456" /></a>
            </div>
            
            <div style="width:78%; height:100%; float:right; text-align:left; font-size:13px">
                <li style="display:inline"><a href="{util->baseUrl}/bookinfo-{$bookinfos.data[pbID].id}.html" class="a5"><strong>{util->setRed p1=$arrayKeyWord p2=$bookinfos.data[pbID].bookname}</strong></a></li>
                <br><br>
                <li style="display:inline">出版社：{$bookinfos.data[pbID].pubname}</li>
                <br><br>
                <li style="display:inline">作者：{$bookinfos.data[pbID].writer}</li>
                <br><br>
                <li style="display:inline">上架时间：{$bookinfos.data[pbID].addtime|truncate:10:""}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;出版时间：{$bookinfos.data[pbID].pubtime|truncate:10:""}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;浏览次数：{$bookinfos.data[pbID].browsertime}&nbsp;次</li>
                <br><br>
                <li style="display:inline">市场价：<img src="{util->baseUrl}/img/mark_green.gif" />&nbsp;<s>{util->moneyFormat p=$bookinfos.data[pbID].oldprice}</s>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <font color="#FF0000">会员价：<img src="{util->baseUrl}/img/mark_red.gif" />&nbsp;{util->moneyFormat p=$bookinfos.data[pbID].newprice}</font>          
                 </li> 
                 <br><br> 
                 <li style="display:inline"><a href="{util->baseUrl}/cart-{$bookinfos.data[pbID].id}-add.html"><img src="{util->baseUrl}/img/button_order.gif" border="0"/></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{util->baseUrl}/bookinfo-{$bookinfos.data[pbID].id}.html"><img src="{util->baseUrl}/img/button_info.gif" border="0"/></a></li>                            
            </div>
            
        </div>
        <div style="width:95%; height:50px; border:1px solid #CCCCCC; text-align:left; line-height:18px; color:#990000; padding:5px">
        {util->unHtml p=$bookinfos.data[pbID].about|truncate:420:"...":false}
        </div>
    </div>
    {/section}  
    {else}
    <div style="width:550px; height:80px; font-size:14px">
        <li style="display: inline; width:100%; color:#FF0000"><img src="{util->baseUrl}/img/mark_telllogin.gif"><br />
                    <strong>对不起，没有查找到您要找的图书！</strong></li>
        <li style="display: inline; width:100%; text-align:left; padding-top:10px; line-height:20px">
        注意：请按如下提示查找您要找的图书：<br />
        &nbsp;&nbsp;·查询关键字之间要求用空格分割<br />
        &nbsp;&nbsp;·请尝试更换其他查选关键字<br />
        &nbsp;&nbsp;·如果没有查找到您要购买的图书，请拨打我公司的服务热线咨询该书相关信息<br />   
        </li>
                    
    </div>
    {/if}
    
    <div style="width:50px; height:10px; font-size:0px"></div>
    {if $bookinfos.countRs > 0}
    <div style="width:930px; height:25px; border-top:1px dotted #CCCCCC; padding-top:5px; text-align:left; padding-left:20px; background-color:#FFFBE5">
          
  
          {if $stype == "simple"}
          <li style="display:inline; padding-left:20px">共查找到相关图书&nbsp;{$bookinfos.countRs}&nbsp;本&nbsp;&nbsp;每页显示&nbsp;{$bookinfos.pageSize}&nbsp;本&nbsp;&nbsp;第&nbsp;{$bookinfos.page}&nbsp;页/共&nbsp;{$bookinfos.countPage}&nbsp;页&nbsp;&nbsp;&nbsp;&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.first}-{$key}-simple.html" class="a1">首页</a>&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.previous}-{$key}-simple.html" class="a1">上一页</a>&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.next}-{$key}-simple.html" class="a1">下一页</a>&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.last}-{$key}-simple.html" class="a1">尾页</a>
          </li>  
          {elseif $stype == "adv"}
          <li style="display:inline; padding-left:20px">共查找到相关图书&nbsp;{$bookinfos.countRs}&nbsp;本&nbsp;&nbsp;每页显示&nbsp;{$bookinfos.pageSize}&nbsp;本&nbsp;&nbsp;第&nbsp;{$bookinfos.page}&nbsp;页/共&nbsp;{$bookinfos.countPage}&nbsp;页&nbsp;&nbsp;&nbsp;&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.first}-{$key}-{$writer}-{$fyear}-{$fmonth}-{$tyear}-{$tmonth}-{$pubid}-{$smalltypeid}-adv.html" class="a1">首页</a>&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.previous}-{$key}-{$writer}-{$fyear}-{$fmonth}-{$tyear}-{$tmonth}-{$pubid}-{$smalltypeid}-adv.html" class="a1">上一页</a>&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.next}-{$key}-{$writer}-{$fyear}-{$fmonth}-{$tyear}-{$tmonth}-{$pubid}-{$smalltypeid}-adv.html" class="a1">下一页</a>&nbsp;
              <a href="{util->baseUrl}/search-{$bookinfos.last}-{$key}-{$writer}-{$fyear}-{$fmonth}-{$tyear}-{$tmonth}-{$pubid}-{$smalltypeid}-adv.html" class="a1">尾页</a>
          </li>                    
         
          {/if}      
         
    </div>   
    {/if}  
</div>
       
