
<div style="width:950px; background-color:#FFFFFF">
    <div style="width:930px; height:20px; background:url({util->baseUrl}/img/title4.gif); border-top:1px solid #CCCCCC; padding-top:3px; padding-left:20px; font-size:13px; text-align:left">
               您当前的位置：明日网上书店&nbsp;>>&nbsp;用户登录向导
    </div>
    <div style="width:930px; height:100px">    
        <div style="width: 18%; height:100%; float:left; padding-top:15px; text-align:right">
            <img src="{util->baseUrl}/img/mark_telllogin.gif" />
        </div> 
        <div style="width: 78%; height:100%; float:right; text-align:left; padding-top:20px; font-size:14px; line-height:25px">
            对不起！您还没有登录本书店，如果您打算购买本站图书或参与本站活动请先注册为本站会员并登录！<br>
           &nbsp;&nbsp;&nbsp;&nbsp; [<a href="{util->baseUrl}/login.html" class="a1">立即登录</a>]&nbsp;&nbsp;[<a href="{util->baseUrl}/register.html" class="a1">免费注册</a>]
        </div> 
              
    </div>
       
</div>
       
