
<div style="width:950px; background-color:#FFFFFF">
    <div style="width:930px; height:20px; background:url({util->baseUrl}/img/title4.gif); border-top:1px solid #CCCCCC; padding-top:3px; padding-left:20px; font-size:13px; text-align:left">
               您当前的位置：明日网上书店&nbsp;>>&nbsp;会员中心
    </div>
    <br />
    <div style="width:930px; height:100px">
        
        <div style="width:200px; height:100%; float:left; border-right:1px dotted #333333; background-color:#FDFBED; padding-top:5px">
            <div style="width:95%; height:25px; padding-top:5px; border:1px solid #0C92AB; text-align:left; padding-left:50px; background:url({util->baseUrl}/img/button_ucenter.gif)">·&nbsp;<a href="{util->baseUrl}/usercenter.html" class="a1">修改个人信息</a></div>
            <div style="width:50px; height:5px; font-size:0px"></div>
            <div style="width:95%; height:25px; padding-top:5px; border:1px solid #0C92AB; text-align:left; padding-left:50px; background:url({util->baseUrl}/img/button_ucenter.gif)">·&nbsp;<a href="{util->baseUrl}/usercenterchangepwd.html" class="a1">修改登录密码</a></div>
            <div style="width:50px; height:5px; font-size:0px"></div>            
            <div style="width:95%; height:25px; padding-top:5px; border:1px solid #0C92AB; text-align:left; padding-left:50px; background:url({util->baseUrl}/img/button_ucenter.gif)">·&nbsp;<a href="{util->baseUrl}/usercenterorder.html" class="a1">我的订单</a></div>
            <div style="width:50px; height:5px; font-size:0px"></div>  
            <div style="width:95%; height:25px; padding-top:5px; border:1px solid #0C92AB; text-align:left; padding-left:50px; background:url({util->baseUrl}/img/button_ucenter.gif)">·&nbsp;<a href="{util->baseUrl}/userfeedback.html" class="a1">意见反馈</a></div>
            <div style="width:50px; height:5px; font-size:0px"></div>  
            <div style="width:95%; height:25px; padding-top:5px; border:1px solid #0C92AB; text-align:left; padding-left:50px; background:url({util->baseUrl}/img/button_ucenter.gif)">·&nbsp;<a href="{util->baseUrl}/qq.html" class="a1">QQ在线咨询</a></div>
            <div style="width:50px; height:5px; font-size:0px"></div> 
            <div style="width:95%; height:25px; padding-top:5px; border:1px solid #0C92AB; text-align:left; padding-left:50px; background:url({util->baseUrl}/img/button_ucenter.gif)">·&nbsp;<a href="{util->baseUrl}/tel.html" class="a1">服务热线</a></div>                                               
        </div>
        
        <div style="width:720px; height:100%; float:right">
            <div style="width:100%; height:22px; background-color:#FFC976; border-top:1px solid #FF7300; text-align:left; padding-top:4px; padding-left:20px">
                用户反馈
            </div>
            <form name="form_feedback" method="post" action="{util->baseUrl}/userfeedback.html" onsubmit="return chkUserfeedback(this)">
            <div style="width:100%; height:180px; text-align:left; padding-top:5px; padding-left:50px">
                 反馈主题：<input type="text" name="title" size="60" class="input" /><br /><br />
          反馈内容：<textarea name="content" cols="60" rows="6" class="input"></textarea><br /><br />      
                 <input type="submit" value="更改" />&nbsp;&nbsp;<input type="reset" value="重置" />
            </div> 
            </form>       
        </div>            
    
    </div>
    <br />   
</div>
       
