<style type="text/css">
    .register_top                                 {width:769px; height:26px; background:url(<?php echo $this->baseUrl('/img/user_reg_top.gif')?>); clear:both;}  
    .register_center                              {width:769px; background:url(<?php echo $this->baseUrl('/img/user_reg_center.gif')?>); clear:both;}  
    .register_center .left                        {width:58%; float:left;} 
    .register_center .left .title                 {width:75%; height:26px; line-height:26px; color:#006600; font-size:14px; text-align:left; clear:both;}
    .register_center .left .field                 {width:75%; height:26px; line-height:26px; font-size:14px; text-align:left; position:relative; clear:both;}
    .register_center .left .alert                 {width:335px; height:22px; line-height:22px; text-align:left; color:#AC2C08; display:none; background:url(<?php echo $this->baseUrl('/img/input_error_mark.jpg')?>); clear:both;}
    .register_center .left .description           {width:75%; height:40px; line-height:26px; text-align:left; color:#666666; font-size:12px; clear:both;}
    .register_center .left .agreeArea             {width:75%; height:125px; text-align:left; display:none; clear:both;}
    .register_center .left .submit                {width:75%; height:40px; text-align:left; font-size:0px; clear:both;}
    .register_center .right                       {position:relative; width:41%; float:right;} 
    .register_bottom                              {width:769px; height:35px; background:url(<?php echo $this->baseUrl('/img/user_reg_bottom.gif')?>); clear:both;}
</style>

<div class="register_top"></div>
<div class="register_center">
    <div class="left">
        <form name="form_register" id="form_register" method="post"  style="padding:0px; margin:0px;">
        <!-- 登录名 -->  
        <div class="title">
 给自己找个登录名：
        </div>
        <div class="field">
            <input type="text" name="netname" id="netname" class="input" maxlength="15" style="width:200px; height:16px; line-height:16px;" onblur="chkInputReg(1)"/>
        </div>
        <div id="chkNetname" class="alert"></div>
        <div class="description">
登录名用来区分注册会员，要求彼此不同
        </div>
        <!-- 登录密码 -->
        <div class="title">
给自己设置个登录密码：
        </div>
        <div class="field">
            <input type="password" name="password" id="password" maxlength="15" class="input" style="width:200px; height:16px; line-height:16px;" onblur="chkInputReg(2)"/>
        </div>
        <div id="chkPassword" class="alert"></div>
        <div class="description">
要求4-16个字符之间
        </div>
        <div id="safeArea" style="width:75%; display:none; clear:both;">
            <ul>
                <li style="width:26%; height:20px; line-height:20px; color:#000000; font-size:14px; border:1px solid #FFFFFF; float:left;">密码安全性：</li>
                <li id="unsafe" style="width:20%; height:20px; line-height:20px; color:#FFFFFF; background-color:#FF0000; border:1px solid #FFFFFF; float:left;">差</li>
                <li id="midsafe" style="width:20%; height:20px; line-height:20px; color:#FF0000; background-color:#CCCCCC; border:1px solid #FFFFFF; float:left;">中</li>
                <li id="safe" style="width:20%; height:20px; line-height:20px; color:#FF0000; background-color:#CCCCCC; border:1px solid #FFFFFF; float:left;">强</li>
            </ul>
        </div>
        <!-- 确认密码 -->
        <div class="title">
确认密码：
        </div>
        <div class="field">
            <input type="password" name="defpassword" id="defpassword" maxlength="15" class="input" style="width:200px; height:16px; line-height:16px;" onblur="chkInputReg(3)"/>
        </div>
        <div id="chkDefpassword" class="alert"></div>
        <div class="description">
再输入一次密码，确保所设置的密码无误
        </div> 
        <!-- E-mail -->
        <div class="title">
E-mail：
        </div>
        <div class="field">
            <input type="text" name="email" id="email" class="input" style="width:200px; height:16px; line-height:16px;" onblur="chkInputReg(4)"/>
        </div>
        <div id="chkEmail" class="alert"></div>
        <div class="description">
通过E-mail与您联系
        </div>
        <!-- 所在地 -->
        <div class="title">
所在地：
        </div>
        <div class="field">
            <?php echo $this->formSelect('p', '-1', array('onchange'=>'changeCity()', 'onblur'=>''), $this->p)?>&nbsp;省(直辖市)　
            <?php echo $this->formSelect('c', '-1', null, array('-1'=>'请选择城市'))?>&nbsp;市   
        </div>
        <div id="chkAddress" class="alert"></div>
        <div class="description">
请从列表中选择您目前所在地
        </div>
        <!-- 验证码 -->
        <div class="title">
验证码：
        </div>
        <div class="field">
            <input type="text" name="vcode" id="vcode" class="input" maxlength="4" style="width:70px; height:16px; line-height:16px;" onblur="chkInputReg(5)"/><img id="vcodeImg" src="<?php echo $this->baseUrl('/common/vcode/w/80/h/30/t/0')?>" style="position:absolute; left:85px; top:-10px;" />　　　　　　　<a href="javascript:changeVcode()" class="a24">看不清，换一张</a>
        </div>
        <div id="chkVcode" class="alert"></div>
        <div class="description">
请将图片中的字符填写到验证码文本框内，字母不区分大小写
        </div>
        <!-- 注册协议 -->
        <div class="title">
查看注册协议：<input type="checkbox" name="agreebtn" id="agreebtn" onclick="showAgreeArea()"/>
        </div>
        <div class="agreeArea" id="agreeArea">
            <textarea name="agreement" id="agreement" class="input" style="width:330px; height:120px; font-size:13px; color:#777777;"><?php echo $this->agreement?></textarea>
        </div>
        <div id="chkAgreement" class="alert"></div>
        <div class="cell_h"></div>
        <!-- 提交按钮 -->
        <div class="submit">
            <img src="<?php echo $this->baseUrl('/img/btn_register.gif')?>" style="cursor:pointer;" onclick="chkInputReg(-1)"/>
        </div> 
        </form>               
    </div>
    
    <div class="right">
        <img src="<?php echo $this->baseUrl('/img/reg_mark.jpg')?>" style="position: absolute; left:-60px; top:120px;"/>
    </div>
   
    <div class="clear"></div>   
   
</div>
<div class="register_bottom"></div>


<script language="javascript">
    //切换城市
    function changeCity()
    {
        $.get("<?php echo $this->baseUrl('/common/city/pindex/"+$("#p").val()+"')?>", null, function(data){
            $("#c").empty();
            $("#c").append(data);
            if($.trim($("#c").val())=="-1"){
                $("#chkAddress").html("　　请选择目前所在城市");
                $("#p").css("border", "1px solid #FF0000");
                $("#c").css("border", "1px solid #FF0000");
                $("#chkAddress").css("display", "block");
            }else{
                $("#chkAddress").html("");
                $("#p").css("border", "1px solid #777777");
                $("#c").css("border", "1px solid #777777");
                $("#chkAddress").css("display", "none");
               
            } 
        });
    }
    //切换验证码图片
    function changeVcode()
    {
         $("#vcodeImg").attr("src", "<?php echo $this->baseUrl('/common/vcode/w/80/h/30/t/0/rand/"+Math.random()+"')?>");   
    }
    //显示注册协议
    function showAgreeArea()
    {
        if($("#agreeArea").css("display")=="none"){
            $("#agreeArea").css("display", "block");
            $("#chkAgreement").html("");
            $("#chkAgreement").css("display", "none");  
        }else{
        	$("#agreeArea").css("display", "none"); 
            $("#chkAgreement").html("　　请查看注册协议");
            $("#chkAgreement").css("display", "block"); 
        }
    }
    //表单验证
    function chkInputReg(flag)
    {
        $.get("<?php echo $this->baseUrl('/user/chk-register/netname/"+encodeURI($("#netname").val())+"')?>", null, function(chkNameReturnData){
            $.get("<?php echo $this->baseUrl('/common/check-vcode/vcode/"+encodeURI($("#vcode").val())+"')?>", null, function(chkVcodeReturnData){

                var k1=false;
                var k2=false;
                var k3=false;
                var k4=false;
                var k5=false;
                var k6=false;
                var k7=false;
                //用户昵称
                if(flag == 1 || flag == -1){
                    if($.trim($("#netname").val())==""){
                        $("#chkNetname").html("　　请输入用户昵称");
                        $("#netname").css("border", "1px solid #FF0000");
                        $("#chkNetname").css("display", "block");
                    }else if($("#netname").val().length < 4 || $("#netname").val().length > 15){
                        $("#chkNetname").html("　　用户昵称应该在4-15位之间");
                        $("#netname").css("border", "1px solid #FF0000");
                        $("#chkNetname").css("display", "block"); 
                    }else if(chkNameReturnData == "Y"){
                        $("#chkNetname").html("　　该昵称已经被占用");
                        $("#netname").css("border", "1px solid #FF0000");
                        $("#chkNetname").css("display", "block"); 
                    }else{
                        $("#chkNetname").html("");
                        $("#netname").css("border", "1px solid #777777");
                        $("#chkNetname").css("display", "none");
                        k1=true;
                    }
                } 
                //登录密码
                if(flag == 2 || flag == -1){
                    if($.trim($("#password").val())==""){
                        $("#chkPassword").html("　　请输入登录密码");
                        $("#password").css("border", "1px solid #FF0000");
                        $("#chkPassword").css("display", "block");
                    }else if($("#password").val().length < 6 || $("#password").val().length > 15){
                        $("#chkPassword").html("　　登录密码应该在6-15位之间");
                        $("#password").css("border", "1px solid #FF0000");
                        $("#chkPassword").css("display", "block"); 
                    }else{
                        $("#chkPassword").html("");
                        $("#password").css("border", "1px solid #777777");
                        $("#chkPassword").css("display", "none");
        			    var p1 = ($("#password").val().search(/[a-zA-Z]/)!=-1)?1:0;
    				    var p2 = ($("#password").val().search(/[0-9]/)!=-1)?1:0;
    				    var p3 = ($("#password").val().search(/[^a-zA-Z0-9_]/)!=-1)?1:0;
    				    var p = p1+p2+p3;
                        
    				    if(p == 1){
                            $("#unsafe").css("color", "#FFFFFF");
                            $("#midsafe").css("color", "#FF0000");
                            $("#safe").css("color", "#FF0000");
                            $("#unsafe").css("background-color", "#FF0000");
                            $("#midsafe").css("background-color", "#CCCCCC");
                            $("#safe").css("background-color", "#CCCCCC");        
        				}else if(p == 2){
                            $("#unsafe").css("color", "#FF0000");
                            $("#midsafe").css("color", "#FFFFFF");
                            $("#safe").css("color", "#FF0000");
                            $("#unsafe").css("background-color", "#CCCCCC");
                            $("#midsafe").css("background-color", "#FF0000");
                            $("#safe").css("background-color", "#CCCCCC"); 
            	        }else if(p == 3){
                            $("#unsafe").css("color", "#FF0000");
                            $("#midsafe").css("color", "#FF0000");
                            $("#safe").css("color", "#FFFFFF");
                            $("#unsafe").css("background-color", "#CCCCCC");
                            $("#midsafe").css("background-color", "#CCCCCC");
                            $("#safe").css("background-color", "#FF0000"); 
                	    }
                	    $("#safeArea").css("display", "block");
                        k2=true;
                    }
                } 
                //确认密码
                if(flag == 3 || flag == -1){
                    if($.trim($("#password").val())==""){
                        $("#chkDefpassword").html("　　请输入确认密码");
                        $("#defpassword").css("border", "1px solid #FF0000");
                        $("#chkDefpassword").css("display", "block");
                    }else if($.trim($("#defpassword").val())!=$.trim($("#password").val())){
                        $("#chkDefpassword").html("　　密码与确认密码不同");
                        $("#defpassword").css("border", "1px solid #FF0000");
                        $("#chkDefpassword").css("display", "block");
                    }else{
                        $("#chkDefpassword").html("");
                        $("#defpassword").css("border", "1px solid #777777");
                        $("#chkDefpassword").css("display", "none");
                	    k3=true;
                    }
                } 
                //E-mail地址
                if(flag == 4 || flag == -1){
                    if($.trim($("#email").val())==""){
                        $("#chkEmail").html("　　请输入E-mail地址");
                        $("#email").css("border", "1px solid #FF0000");
                        $("#chkEmail").css("display", "block");
                    }else if(!$("#email").val().match(/^.+@.+$/)){
                        $("#chkEmail").html("　　E-mail地址输入有误");
                        $("#email").css("border", "1px solid #FF0000");
                        $("#chkEmail").css("display", "block");
                    }else{
                        $("#chkEmail").html("");
                        $("#email").css("border", "1px solid #777777");
                        $("#chkEmail").css("display", "none");
                        k4=true;
                    }
                } 
                //所在地
                if(flag == -1){
                    if($.trim($("#c").val())=="-1"){
                        $("#chkAddress").html("　　请选择目前所在城市");
                        $("#p").css("border", "1px solid #FF0000");
                        $("#c").css("border", "1px solid #FF0000");
                        $("#chkAddress").css("display", "block");
                    }else{
                        $("#chkAddress").html("");
                        $("#p").css("border", "1px solid #777777");
                        $("#c").css("border", "1px solid #777777");
                        $("#chkAddress").css("display", "none");
                        k5=true;
                    }
                } 
                //验证码
                if(flag == 5 || flag == -1){
                    if($.trim($("#vcode").val())==""){
                        $("#chkVcode").html("　　请输入验证码");
                        $("#vcode").css("border", "1px solid #FF0000");
                        $("#chkVcode").css("display", "block");
                    }else if(chkVcodeReturnData == "N"){
                        $("#chkVcode").html("　　验证码输入有误");
                        $("#vcode").css("border", "1px solid #FF0000");
                        $("#chkVcode").css("display", "block");
                    }else{
                        $("#chkVcode").html("");
                        $("#vcode").css("border", "1px solid #777777");
                        $("#chkVcode").css("display", "none");
                        k6=true;
                    }
                } 
                //注册协议
                if(flag == -1){
                    if(!$("#agreebtn").attr("checked")){
                        $("#chkAgreement").html("　　请查看注册协议");
                        $("#chkAgreement").css("display", "block");
                        return false;      
                    }else{
                        $("#chkAgreement").html("");
                        $("#chkAgreement").css("display", "none");
                        k7=true;
                    }
                } 
                //提交表单
                if(flag == -1 && k1 && k2 && k3 && k4 && k5 && k6 && k7){
                    $("#form_register").submit();               
                } 
            });
        });    
    }
</script>