<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php 
            echo $this->headMeta()->setHttpEquiv('content-type', 'text/html; charset=utf-8')
                                  ->setHttpEquiv('keywords', $this->escape($this->keywords))
                                  ->setHttpEquiv('description', $this->escape($this->description))
                                  ->appendHttpEquiv('x-ua-compatible', 'ie=7');
        ?>
        <?php echo $this->headTitle($this->escape($this->title))?>
        <?php echo $this->headLink()->setStylesheet($this->baseUrl('/css/style.css'))?>
        <style type="text/css">
            .default-body                {background:url(<?php echo $this->baseUrl('/img/bg.jpg')?>) repeat-x 0 0; background-color:#E7F6FB;}
            .default-top                 {width:980px; height:30px; clear:both;}
            .default-top .li1            {width:600px; height:30px; line-height:30px; text-align:left; color:#FFFFFF; float:left;}
            .default-top .li2            {width:200px; height:30px; line-height:30px; text-align:right; color:#FFFFFF; float:right;}
            .default-main                {width:980px; background-color:#FFFFFF; clear:both;}
        </style>
    </head>
    <body class="default-body">
        <script src="<?php echo $this->baseUrl('/js/jquery.js')?>"></script>
        <div class="default-top">
            <ul>
                <li class="li1"><a href="#" class="a1">设为首页</a>　/　<a href="#" class="a1">加为收藏</a>　/　<a href="<?php echo $this->baseUrl('/admin')?>" class="a1">管理中心</a></li>
                <li class="li2"><?php if($this->loginUser==null):?><a href="<?php echo $this->baseUrl('/user/register')?>" class="a1">注册</a>　/　<a href="<?php echo $this->baseUrl('/user/login')?>" class="a1">登录</a><?php else:?>当前用户：<a href="" class="a1"><?php echo $this->escape($this->loginUser['netname'])?></a>　/　<a href="<?php echo $this->baseUrl('/user/logout')?>" class="a1">退出</a><?php endif;?></li>
            </ul>
        </div>
        <div class="default-main">
            <?php echo $this->render('default_header.phtml')?>  
            <?php echo $this->layout()->content;?>
            <?php echo $this->render('default_footer.phtml')?>
        </div>
        <div class="cell_h"></div>
    </body>
</html>