<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php 
            echo $this->headMeta()->setHttpEquiv('content-type', 'text/html; charset=utf-8')
                                  ->setHttpEquiv('keywords', $this->escape($this->keywords))
                                  ->setHttpEquiv('description', $this->escape($this->description))
                                  ->appendHttpEquiv('x-ua-compatible', 'ie=7');
        ?>
        <?php echo $this->headTitle($this->escape($this->title))?>
        <?php echo $this->headLink()->setStylesheet($this->baseUrl('/css/style.css'))?>
        <?php echo $this->headScript()->setFile($this->baseUrl('/js/jquery.js'))?>
    </head>
    <body>
        <?php echo $this->render('user_header.phtml')?>  
        <?php echo $this->layout()->content;?>
        <?php echo $this->render('user_footer.phtml')?>
    </body>
</html>