<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
<title>明日网上书店管理中心</title>
<link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<noscript><iframe src="*.html"></iframe></noscript>
<frameset cols="182, *">
	<frame src="{util->baseUrl}/admin-left.php" name="leftwindow">
	<frame src="{util->baseUrl}/admin-main.php" name="mainwindow">
</frameset><noframes></noframes>

